### ISSUE TITLE
Various exceptions when running Wallaby on simple Jest project

### ISSUE THREAD

**Issue by endragor** [wallabyjs/public#112]
When stopping and running Wallaby.js subsequently for my current fork of wallaby-jest-example (https://github.com/endragor/wallaby-jest-sample), in ~50% times you'll get exceptions as shown below.

Also, in the same project, if you copy-paste any test file (renaming it) while Wallaby is running, you'll get guaranteed `Cannot read property '0' of undefined` errors in the log.

![wallaby_jest_exceptions](https://cloud.githubusercontent.com/assets/2417849/7685000/faff6cf2-fda3-11e4-8d9f-0899494467f7.png)

**Comment by endragor** [comment]
FYI setting `workers.recycle` to `true` solves these issues for me

**Comment by ArtemGovorov** [comment]
Thanks for the sample. Fixed in core 1.0.46 (will update itself automatically).

**Comment by endragor** [comment]
I still get same errors with v1.0.46 with the same repo, if I don't set `workers.recycle` to `true`.

**Comment by ArtemGovorov** [comment]
I can't reproduce it anymore, can you try making any change to your config file and restarting wallaby? It will reset its cache (though I don't think it is an issue in this case).

**Comment by endragor** [comment]
Can't reproduce it now. Did several things, including invalidating IDEA caches, refreshing node_modules,  changing config file and probably something else. Not sure which of them helped.
Anyway, I think the issue can be closed now.

**Comment by endragor** [comment]
Occasionally I still get errors like `Cannot read property '105' of undefined`. No clear way to reproduce though.

**Comment by ArtemGovorov** [comment]
How frequently does it happen? Like once in a minute of coding, 10 minutes/an hour?
Does `workers: {recycle: true}` eliminate the issue or it's still reproducible with it?

**Comment by endragor** [comment]
It happens pretty often, actually. I just reproduced this on the sample project from my repo - took a couple of minutes. Just duplicate the test in `sum-test.js` many times and do some changes - like changing description strings in `describe()` and `it()`. You should get the error shortly.

**Comment by ArtemGovorov** [comment]
Awesome, thanks, will try to reproduce it in the repo.

**Comment by ArtemGovorov** [comment]
Reproduced, will be fixing it shortly.

**Comment by ArtemGovorov** [comment]
Should be fixed in 1.0.58, let me know if it works for you now.

**Comment by endragor** [comment]
Seems to be working now. Thanks!
