### ISSUE TITLE
Jest test environment docblock support

### ISSUE THREAD

**Issue by jgoz** [wallabyjs/public#1216]
### Issue description or question

Does Wallaby support Jest's [`@jest-environment` docblock](https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string)?

I have a few tests that should be executed in an alternate environment, so I'm using the docblock in those specific test files. The tests execute properly using the Jest CLI, but it appears as though the environment is not being set correctly when executing with Wallaby.

### Wallaby.js configuration file

<details>
  <summary>wallaby.js</summary>

```javascript
const path = require("path");

const packageDirs = [
    "packages/core",
    "packages/foo"
];

module.exports = function(w) {
    for (const pkg of packageDirs) {
        const p = path.delimiter + path.join(w.localProjectDir, pkg, "node_modules");
        process.env.NODE_PATH += p;
    }
    return {
        files: [
            "jest.config.js",
            "tsconfig.json",
            "packages/core/src/**/*.{ts,js}",
            "!packages/core/src/**/*.tests.*",
            "packages/foo/src/**/*.{ts,js}",
            "!packages/foo/src/**/*.tests.*"
        ],
        tests: [
            "packages/core/src/**/*.tests.ts",
            "packages/foo/src/**/*.tests.{ts,js}"
        ],
        env: {
            type: "node",
            params: {
                env: "NODE_ENV=test"
            }
        },
        testFramework: "jest",
        setup: function(wallaby) {
            wallaby.testFramework.configure(require("./jest.config"));
        }
    };
};
```

</details>

### Code editor or IDE name and version

Visual Studio Code v1.13.1

### OS name and version

OSX 10.12

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by jgoz** [comment]
@ArtemGovorov Thanks for the quick response. I've updated to the latest core (1.0.447) and am still experiencing the issue, but I think I know why.

My codebase is in TypeScript (using `ts-jest`) and while the `@jest-environment` comment is present in my original TS file, it does not exist in the instrumented JS output. Is there any way to preserve docblocks in instrumented output?

**Comment by ArtemGovorov** [comment]
@jgoz It's strange because the fix we have published should address the issue. I was able to reproduce the issue before the fix, but now it's all working for me.

I have created [this sample repo branch](https://github.com/wallabyjs/wallaby-jest-sample/tree/ts), where Jest [`test testEnvironment` is set to `node` by default](https://github.com/wallabyjs/wallaby-jest-sample/blob/ts/jest.config.js#L2), then I [override it by  the block comment in the TypeScript test file](https://github.com/wallabyjs/wallaby-jest-sample/blob/ts/__tests__/sum-test.ts#L2) and the test asserts [that jsdom is being loaded](https://github.com/wallabyjs/wallaby-jest-sample/blob/ts/__tests__/sum-test.ts#L7) (if the block comment is removed, the test starts failing).

Try the repo to see if it's working for you, and is so, please try adding the missing bits from your project so that the issue could be reproduced.

**Comment by jgoz** [comment]
@ArtemGovorov I was able to reproduce my behaviour in your sample repository by setting `strict: true` in `tsconfig.json`. Without that option, the `/** jest-environment jsdom */` comment is emitted properly in the instrumented `sum-test.js`. But with the option, it emits `'use strict';` and not the comment.

This is my branch: https://github.com/jgoz/wallaby-jest-sample/tree/ts-strict-fail

Side note: if I run `tsc` in my fork, `sum-test.js` has `"use strict"; /** jest-environment jsdom */`, which does _not_ work using the Jest CLI. If I manually move the docblock before the strict pragma, it _does_ work.

**Comment by ArtemGovorov** [comment]
@jgoz Thanks for the repo and for the analysis, it was very helpful! The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.

After the update, you may need to clear wallaby cache (by editing wallaby config file and starting wallaby, even a space anywhere in the config will do, you may revert it back after the cache is cleared).

**Comment by jgoz** [comment]
All ✅ now!

Thanks @ArtemGovorov for the speedy resolution.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for checking!
