### ISSUE TITLE
Webpack es2015 module modification issue

### ISSUE THREAD

**Issue by iamchucky** [wallabyjs/public#1414]
### Issue description or question

When using `"module": "es2015"` in the `tsconfig.spec.json`, wallaby seems to have problem finding the new exported function.

Please look at following sample repo that's created using Angular CLI:
https://github.com/iamchucky/wallaby-symlink-repo

To reproduce:
- start wallaby
- uncomment `module1/foo.spec.ts#L9`
- uncomment `module1/foo.spec.ts#L1`
- uncomment `module1/foo.ts#L1-3`
- left with error: 
```
TypeError: Object(...) is not a function​​
      at Object.<anonymous> ​src/modules/module1/foo.spec.ts:9:8​
```

Note that the steps above is fine with `"module": "commonjs", "target": "es5"` in the `tsconfig.spec.json` or if restart wallaby.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: ['raw-loader', 'css-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.styl', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.18.1

### OS name and version

macOS High Sierra 10.13.1

**Comment by ArtemGovorov** [comment]
It looks like an issue with (wallaby-) webpack incremental compilation issue. While we are investigating the issue, you may override your compiler options module to `CommonJs` in your wallaby config, this should be enough:

```javascript
var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs'; //<--
```

**Comment by ArtemGovorov** [comment]
We have updated [`wallaby-webpack` package](https://github.com/jeffling/wallaby-webpack) to support the scenario. Please update your wallaby-webpack to 3.9.0, and the issue should be fixed for you.

**Comment by iamchucky** [comment]
After I update `wallaby-webpack` to 3.9.0, it is still not able to pickup the changes with `es2015` module. Am I missing something?

**Comment by ArtemGovorov** [comment]
Sorry, apparently the fix was only working for some scenarios. We have released a new version with more fixes.

Please update your `wallaby-webpack` to 3.9.1, and [Wallaby Core to the latest v1.0.527](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), it should work.

**Comment by iamchucky** [comment]
It works now! thanks for the fix!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for checking!
