### ISSUE TITLE
VS Code/Typescript : Wallaby does not apply file changes.

### ISSUE THREAD

**Issue by Esya** [wallabyjs/public#1658]
### Issue description or question

All of the sudden, in my test suite (Wallaby might have updated itself in the background while I wasn't looking), wallaby does not apply the differences in code I'm making in real time. It seems to detect that there is a modification happening, but does not act on it. If I use `restart: true` or manually restart wallaby, it works (But I'll have to restart it again afterwards)

As an example :

*Before, when I just started wallaby*
![2018-05-15-155943_1357x685_scrot](https://user-images.githubusercontent.com/937179/40061400-1bb2cefe-5859-11e8-9887-03a20d0d4800.png)

*After making a few code changes (And waiting)*
![2018-05-15-160004_1386x775_scrot](https://user-images.githubusercontent.com/937179/40061403-1d8fedba-5859-11e8-8e81-7a545ae50625.png)

### Wallaby.js configuration file

```javascript
module.exports = function (w) {
    console.log(process.version)
    process.env.NODE_ENV = 'test';

    return {
        files: [{
                pattern: 'src/routes.ts',
                instrument: false
            },
            {
                pattern: 'src/index.ts',
                instrument: false
            },
            'test/fixtures/*.ts',
            'src/*.ts',
            'src/controllers/*.ts',
            'config/config.yml',
            'config/config.override.yml'
        ],

        tests: [
            'test/*.ts'
        ],

        env: {
            type: 'node'
        },
        // or any other supported testing framework:
        // https://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks
        testFramework: 'mocha',
        setup: function (wallaby) {
            require("should");
            var mocha = wallaby.testFramework;
            mocha.timeout(15000);
        },
        workers: {
            initial: 1,
            regular: 1
        },
        // hints: {
        //     ignoreCoverage: /istanbul ignore/
        // },
        delays: {
            run: 500
        },
        debug: true
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.23

### OS name and version

Arch Linux, 4.14.40-1-lts #1 SMP Wed May 9 13:00:32 CEST 2018 x86_64 GNU/Linux

### Additional detail

What is confusing to me is that in my `~/.vscode-oss/extensions/WallabyJs.wallaby-vscode-1.0.83/projects` folder, while it's running, and while it seems that Wallaby does not pickup the code changes, I see my edits in : 

`./instrumented/src/controllers/scheduling.controller.ts` (Updated in realtime with my changes)
`./instrumented/src/controllers/scheduling.controller.js` (Transpiled from typescript with my changes in it)

Also, I'm not able to provide a public repository where this happens, as it could be related to the size of the project. (I could provide it in private as a last resort)

### Verbose output : 

After Wallaby starts and successfully runs the test, I make a simple change to the project, it runs the test again, but with the old codebase it seems, since the code succeeds again, and I do not have my updated output.

```
[Info]​​​​​ v9.4.0
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:project Wallaby config: /home/esya/Documents/Git/microservice-scheduling/wallaby.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: config/config.yml
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.588
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: src/authentication.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: src/index.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: src/microservice-scheduling.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: src/optimizer.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: src/routes.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: src/task.interfaces.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: src/taskPlanner.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: src/taskService.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: src/tourSolver.interfaces.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: test/Task.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: test/TaskPlanner.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: test/TaskService.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: test/optimizer.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: test/scheduling.behavior.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: test/scheduling.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: test/task.behavior.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: test/tests.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: src/controllers/scheduling.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: src/controllers/task.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: test/fixtures/checklistAnswers.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:39 GMT wallaby:fs File added: test/fixtures/checklistTemplate.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:fs File system scan has finished by timeout
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project File cache: /home/esya/.vscode-oss/extensions/WallabyJs.wallaby-vscode-1.0.83/projects/8b3ba3beb17142c3
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:uiService Listening port 51235
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:workers Parallelism for initial run: 1, for regular run: 1
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:workers Starting run worker instance #0
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:workers Web server is listening at 34837
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process src/authentication.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process src/index.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project File src/index.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project No preprocessors configured for src/index.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Writing to disk and caching processed file src/index.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process src/microservice-scheduling.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process src/optimizer.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process src/routes.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project File src/routes.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project No preprocessors configured for src/routes.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Writing to disk and caching processed file src/routes.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process src/task.interfaces.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process src/taskPlanner.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process src/taskService.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process src/tourSolver.interfaces.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process test/Task.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process test/TaskPlanner.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process test/TaskService.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process test/optimizer.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process test/scheduling.behavior.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process test/scheduling.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process test/task.behavior.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process test/tests.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process src/controllers/task.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process test/fixtures/checklistAnswers.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Re-instrumenting original file because its ID has changed
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Preparing to process test/fixtures/checklistTemplate.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:40 GMT wallaby:workers Started run worker instance (delayed) #0
​​​​​[Info]​​​​​ v9.4.0
​​​​​[Info]​​​​​ v9.4.0
​​​​​[Info]​​​​​ v9.4.0
​​​​​[Info]​​​​​ v9.4.0
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for src/optimizer.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File src/optimizer.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for src/optimizer.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file src/optimizer.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for src/microservice-scheduling.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for src/taskPlanner.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File src/taskPlanner.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for src/taskPlanner.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file src/taskPlanner.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File src/microservice-scheduling.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for src/microservice-scheduling.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file src/microservice-scheduling.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for src/authentication.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File src/authentication.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for src/authentication.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file src/authentication.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for src/taskService.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for src/tourSolver.interfaces.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File src/taskService.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for src/taskService.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file src/taskService.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for test/Task.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File src/tourSolver.interfaces.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for src/tourSolver.interfaces.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file src/tourSolver.interfaces.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for test/TaskService.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File test/Task.test.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for test/Task.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file test/Task.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File test/TaskService.test.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for test/TaskService.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for test/optimizer.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file test/TaskService.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for test/scheduling.behavior.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for src/task.interfaces.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File test/optimizer.test.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for test/optimizer.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file test/optimizer.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for test/scheduling.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File test/scheduling.behavior.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for test/scheduling.behavior.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file test/scheduling.behavior.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File src/task.interfaces.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for src/task.interfaces.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file src/task.interfaces.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for test/task.behavior.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File test/scheduling.test.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for test/scheduling.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file test/scheduling.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File test/task.behavior.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for test/task.behavior.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file test/task.behavior.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for test/fixtures/checklistAnswers.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for test/tests.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for src/controllers/task.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File test/fixtures/checklistAnswers.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for test/fixtures/checklistAnswers.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file test/fixtures/checklistAnswers.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for test/TaskPlanner.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for test/fixtures/checklistTemplate.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File src/controllers/task.controller.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for src/controllers/task.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file src/controllers/task.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File test/TaskPlanner.test.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for test/TaskPlanner.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file test/TaskPlanner.test.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File test/tests.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for test/tests.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file test/tests.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File test/fixtures/checklistTemplate.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for test/fixtures/checklistTemplate.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file test/fixtures/checklistTemplate.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File cache requires some updates, waiting required files from IDE
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:extended-core New document or complex document change
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File src/controllers/scheduling.controller.ts changes are patches only: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Preparing to process src/controllers/scheduling.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:processor No compilers found for src/controllers/scheduling.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File src/controllers/scheduling.controller.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project No preprocessors configured for src/controllers/scheduling.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Writing to disk and caching processed file src/controllers/scheduling.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project File src/controllers/scheduling.controller.ts changes saved, store ts: 1526392957280, change ts: 1526393021321
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Stopping process pool
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:postprocessor New TypeScript language service is required
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:postprocessor TypeScript compiler options module (before tsconfig.json): undefined
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:41 GMT wallaby:postprocessor TypeScript compiler options module (after tsconfig.json): 1
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process src/routes.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process src/index.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process test/fixtures/checklistAnswers.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process test/fixtures/checklistTemplate.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process src/authentication.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process src/microservice-scheduling.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process src/optimizer.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process src/task.interfaces.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process src/taskPlanner.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process src/taskService.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process src/tourSolver.interfaces.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process src/controllers/scheduling.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process src/controllers/task.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process test/Task.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process test/TaskPlanner.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process test/TaskService.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process test/optimizer.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process test/scheduling.behavior.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process test/scheduling.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process test/task.behavior.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Preparing to process test/tests.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project File src/routes.js is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project File src/index.js is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled test/fixtures/checklistAnswers.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting test/fixtures/checklistAnswers.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled test/fixtures/checklistTemplate.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting test/fixtures/checklistTemplate.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled src/authentication.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting src/authentication.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled src/microservice-scheduling.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting src/microservice-scheduling.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled src/optimizer.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting src/optimizer.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled src/task.interfaces.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting src/task.interfaces.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled src/taskPlanner.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting src/taskPlanner.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled src/taskService.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting src/taskService.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled src/tourSolver.interfaces.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting src/tourSolver.interfaces.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled src/controllers/scheduling.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting src/controllers/scheduling.controller.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled src/controllers/task.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting src/controllers/task.controller.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled test/Task.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting test/Task.test.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled test/TaskPlanner.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting test/TaskPlanner.test.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled test/TaskService.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting test/TaskService.test.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled test/optimizer.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting test/optimizer.test.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled test/scheduling.behavior.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting test/scheduling.behavior.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled test/scheduling.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting test/scheduling.test.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled test/task.behavior.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting test/task.behavior.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Processing compiled test/tests.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Instrumenting test/tests.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for src/routes.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for src/index.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file src/routes.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file src/index.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for test/fixtures/checklistAnswers.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for test/fixtures/checklistTemplate.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for src/authentication.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for src/microservice-scheduling.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for src/optimizer.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for src/task.interfaces.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for src/taskPlanner.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for src/taskService.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for src/tourSolver.interfaces.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for src/controllers/scheduling.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for src/controllers/task.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for test/Task.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for test/TaskPlanner.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for test/TaskService.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for test/optimizer.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for test/scheduling.behavior.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for test/scheduling.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for test/task.behavior.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project No preprocessors configured for test/tests.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file test/fixtures/checklistAnswers.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file test/fixtures/checklistTemplate.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file src/authentication.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file src/microservice-scheduling.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file src/optimizer.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file src/task.interfaces.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file src/taskPlanner.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file src/taskService.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file src/tourSolver.interfaces.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file src/controllers/scheduling.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file src/controllers/task.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file test/Task.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file test/TaskPlanner.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file test/TaskService.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file test/optimizer.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file test/scheduling.behavior.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file test/scheduling.test.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file test/task.behavior.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Writing to disk and caching processed file test/tests.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Test run started; run priority: 3
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:project Running all tests
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:workers Starting test run, priority: 3
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #zn77o]
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #zn77o]
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #zn77o]
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:42 GMT wallaby:workers [worker #0, session #zn77o] Running tests in sandbox
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:44 GMT wallaby:workers [zn77o] Loaded 2 test(s)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:44 GMT wallaby:workers [zn77o] Test executed: /Scheduling/test should 200
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:44 GMT wallaby:workers [zn77o] Run 1 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:44 GMT wallaby:workers [zn77o] Sandbox is responsive, closing it
​​​​​[Info]​​​​​ Finished executing 1 affected test(s)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:44 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:44 GMT wallaby:project Processed console.log entries
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:44 GMT wallaby:project Processed loading sequences
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:44 GMT wallaby:project Processed executed tests
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:44 GMT wallaby:project Processed code coverage
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:44 GMT wallaby:project Test run result processed and sent to IDE
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:47 GMT wallaby:fs File changed in editor: src/controllers/scheduling.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:47 GMT wallaby:project File src/controllers/scheduling.controller.ts changes are patches only: true
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:47 GMT wallaby:project Caching file [19] in memory
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:47 GMT wallaby:project Preparing to process src/controllers/scheduling.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:47 GMT wallaby:project No compilers configured for src/controllers/scheduling.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:47 GMT wallaby:project File src/controllers/scheduling.controller.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:47 GMT wallaby:project No preprocessors configured for src/controllers/scheduling.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:47 GMT wallaby:project Writing to disk and caching processed file src/controllers/scheduling.controller.ts
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:47 GMT wallaby:project File src/controllers/scheduling.controller.ts changes saved, store ts: 1526392957280, change ts: 1526393027637
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Preparing to process src/controllers/scheduling.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Processing compiled src/controllers/scheduling.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Instrumenting src/controllers/scheduling.controller.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project No preprocessors configured for src/controllers/scheduling.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Writing to disk and caching processed file src/controllers/scheduling.controller.js
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Test run started; run priority: 2
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:workers Starting test run, priority: 2
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #152b1]
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #152b1]
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #152b1]
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:workers [worker #0, session #152b1] Running tests in sandbox
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:workers [152b1] Loaded 2 test(s)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:workers [152b1] Test executed: /Scheduling/test should 200
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:workers [152b1] Run 1 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:workers [152b1] Sandbox is responsive, closing it
​​​​​[Info]​​​​​ Finished executing 1 affected test(s)
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Processed console.log entries
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Processed loading sequences
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Processed executed tests
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Processed code coverage
​​​​​[Info]​​​​​ Tue, 15 May 2018 14:03:48 GMT wallaby:project Test run result processed and sent to IDE
```

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. I have tried reproducing the issue using your config files and source files on the screenshots, but everything is workign for me:
![wallaby](https://user-images.githubusercontent.com/979966/40090413-dfb1d41c-58f4-11e8-8dc1-4ae87b6db2b8.gif)

so I must be missing some details specific to your project. 
I have created this [sample repo with my attempt](https://github.com/ArtemGovorov/wallaby-1658). Could you please take a look, clone, `npm i` and run wallaby to see if it's working for you? If it is, please see if you spot/try adding any details that are different from your real project in order to reproduce the issue. If you get stuck reproducing the issue, please share the private repo, I'm happy to take a look and investigate.

**Comment by Esya** [comment]
Thank you for your quick reply. I've tried on your repo - And it works.
What's strange to me is that really, Wallaby picks up the fact that the file has changed, and runs the test again (You can see on my example that the logged Date changes, as the code runs again) but does not pick up the test.

I've found some detail that could be of use to you. Currently, the entry point of our file looks something like this : 

```
import { app } from '@company/microservice-base'
import { RegisterRoutes } from './routes';
import * as express from 'express';

import { SchedulingController } from './controllers/scheduling.controller'
import { TaskController } from './controllers/task.controller'

@Service()
export class MicroserviceScheduling {
    public app: any;
    public server;

    constructor() {
        RegisterRoutes(app);

        /* istanbul ignore if  */
        if (!module.parent) {
            this.server = app.listen(3000);
        }
        this.app = app;

    }
}
```

Well it turns out that if we use `app` locally, instead of pulling it from our other package, it works, like so : 

```
    constructor() {
        app = express();
        RegisterRoutes(app);
        ....
```

The problem is, our base package actually plugs middlewars and does a lot of other things like managing authentication..

Could it be because it goes "too deep" in the callstack to actually find the code changes etc. ?
I've tried adding `node_modules/@company/microservice-base/**` to the files in `wallaby.js`, and **it works** but it is slow to the point where it's just painful (Because it loads up thousands of files)

**Comment by ArtemGovorov** [comment]
> Could it be because it goes "too deep" in the callstack to actually find the code changes etc. ?

Never seen anything like this. Wallaby works by instrumenting source files, so if a test causes a line of code/module to be executed while it's running, then wallaby creates a dependency and will run the test when the line/module changes.

> What's strange to me is that really, Wallaby picks up the fact that the file has changed, and runs the test again (You can see on my example that the logged Date changes, as the code runs again) but does not pick up the test.

Sorry, not sure if I'm following. In the sample, that I have created wallaby reacts for both test and source file changes. Also, from the log file that you've shared, it looks like wallaby is running related tests. Could you please elaborate a bit on what did you mean there?

If you could add the missing bits (real middleware/auth is obviously not required) to my sample repo so that I could reproduce the issue, I'd be able to tell what's going on fairly quickly.

**Comment by Esya** [comment]
Sorry if I'm not clear enough. I'm making a very simple repo (I've just deleted all of our code from our actual repository) where you'll be able to try it. In the meantime, I've made a screencap of this : 

[Screencap of the issue](https://youtu.be/q6yadJlVyVY)

The underlying module, in this usecase, only returns an express app with nothing special added on it. in our actual usecase, we need to import it from another module where we actually plug middlewares etc.

Please let me know your thoughts on this.

**Comment by Esya** [comment]
I've also sent you an invite to a private repository where the issue can be reproduced, on your user @ArtemGovorov

**Comment by ArtemGovorov** [comment]
@Esya Thanks for the repo, but unfortunately the tests don't run in it (because the `@company/microservice-base` module is missing), so I can't reproduce the issue.

However, thanks to your video recording, I think I know what the issue is. Looks like it may be related related to the `@company/microservice-base` [node module caching](https://wallabyjs.com/docs/integration/node.html#node-process-reuse). Your `app` may be cached so the newer controller version when you change it doesn't get called. Try clearing the module cache in the wallaby `setup` function as the docs article suggests:

```diff
module.exports = wallaby => {
  return {
    ...
+    setup: function (w) {
+      // don't forget to correct the module name here 
+      delete require.cache[require.resolve('@company/microservice-base')]; 
+    }
  };
};
```

**Comment by Esya** [comment]
Indeed, I committed with a symlink - I've just fixed that and you can try it now, my bad!
Your solution saddly does not work, and I had tried that already previously.

**Comment by Esya** [comment]
@ArtemGovorov I've also tried creating a new instance of the class that registers my routes, and it does not work either. I'm not too sure what's happening here.

**Comment by ArtemGovorov** [comment]
@Esya Thanks for updating the repo, but it still doesn't run tests (neither wallaby, nor plain mocha). Looks like you have committed Typescript files instead of a compiled module. Please update the repo so that the tests could run and let me know, I'm happy to have a look.

**Comment by Esya** [comment]
@ArtemGovorov Gosh sorry it's 5am here, so a bit sloppy. I've fixed that and added the compiled `lib` folder that is originally gitignore'd.

**Comment by ArtemGovorov** [comment]
@Esya Thanks. As I was suspecting, it was a caching issue. Another way of clearing the module cache [described in the docs](https://wallabyjs.com/docs/integration/node.html#node-process-reuse) helped, I have [committed the working change](https://github.com/Esya/example-wallaby-bug/commit/d96766ee2e6a8dd146b92ade5d0554d790098f1e).
