### ISSUE TITLE
Typescript cli file with #!/usr/bin/env node

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1933]
### Issue description or question
Typescript files cannot contain  `#!/usr/bin/env node`.

```
Failed to parse src/example.ts, SyntaxError: Unexpected character '#' (1:0)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Example: [chrisblossom/wallaby-issue-1933
](https://github.com/chrisblossom/wallaby-issue-1933)

### Wallaby.js configuration file

```javascript
'use strict';

module.exports = (wallaby) => {
    return {
        files: [
            { pattern: '.babelrc+(.js|)', instrument: false },
            { pattern: 'tsconfig.json', instrument: false },
            'src/**/*.ts',
            'jest.config.js',
            '.env',
            '*/**/__snapshots__/*.snap',
            '!src/**/*.test.ts',
        ],

        tests: [
            'src/**/*.test.ts',
        ],

        compilers: {
            '**/*.ts': wallaby.compilers.babel(),
        },

        hints: {
            ignoreCoverage: /ignore coverage/,
        },

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: (w) => {
            /**
             * https://github.com/wallabyjs/public/issues/1268#issuecomment-323237993
             */
            if (w.projectCacheDir !== process.cwd()) {
                process.chdir(w.projectCacheDir);
            }

            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');

            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version

`WebStorm 2018.3.1 EAP`

### OS name and version

``macOS 10.14.1``

**Comment by smcenlly** [comment]
Thanks for the sample repo! I've created a pull request with the updated configuration. To fix the problem, I updated your wallaby configuration to require your `.babelrc.js` configuration and then passed it to `wallaby.compilers.babel`.

I've created a pull request for you [here](https://github.com/chrisblossom/wallaby-issue-1933/pull/1). You can also see the changes in the diff below.

```diff
'use strict';

module.exports = (wallaby) => {
+   var babelConfig = require('./.babelrc');

    return {
        files: [
            { pattern: '.babelrc+(.js|)', instrument: false },
            { pattern: 'tsconfig.json', instrument: false },
            'src/**/*.ts',
            'jest.config.js',
            '.env',
            '*/**/__snapshots__/*.snap',
            '!src/**/*.test.ts',
        ],

        tests: [
            'src/**/*.test.ts',
        ],

        compilers: {
-           '**/*.ts': wallaby.compilers.babel(),
+           '**/*.ts': wallaby.compilers.babel(babelConfig),
        },

        hints: {
            ignoreCoverage: /ignore coverage/,
        },

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: (w) => {
            /**
             * https://github.com/wallabyjs/public/issues/1268#issuecomment-323237993
             */
            if (w.projectCacheDir !== process.cwd()) {
                process.chdir(w.projectCacheDir);
            }

            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');

            w.testFramework.configure(jestConfig);
        },
    };
};
```

**Comment by ArtemGovorov** [comment]
> Why is this additional configuration needed when it typically is not?

Good question. We have done some more investigation and apparently this additional config is just a red herring. We have fixed the issue and released new [core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) with the fix (after the update it should work with your original config).

**Comment by chrisblossom** [comment]
Thanks @ArtemGovorov. I updated both vscode and webstorm but the issue still seems to be there.

**Comment by ArtemGovorov** [comment]
@chrisblossom Try now, looks like the release upload had been delayed a bit.

**Comment by chrisblossom** [comment]
Works, thanks!
