### ISSUE TITLE
Jest + TypeScript + Inline Snapshots are not working

### ISSUE THREAD

**Issue by dicarlo2** [wallabyjs/public#2060]
### Issue description or question

Using `toMatchInlineSnapshot` always results in `Error: Jest: Couldn't locate all inline snapshots.`. After playing around with the settings and taking a look at the cached transformation it appears that wallaby's typescript compiler is not emitting inline sourcemaps.

See full example: https://github.com/dicarlo2/wallaby-create-react-app-ts/commit/4e5031258fcacd76c0e12fe96cbeb75c71755348

### Wallaby.js configuration file

Wallaby.js App v1.0.54, Core v1.0.679

https://github.com/dicarlo2/wallaby-create-react-app-ts/blob/master/wallaby.js

### Code editor or IDE name and version

Visual Studio Code v1.33.1
### OS name and version

OSX

**Comment by smcenlly** [comment]
Thanks for reporting this problem. This has been fixed and is available in the latest version of Wallaby core, v1.0.680.

**Comment by dicarlo2** [comment]
@smcenlly Awesome, thanks!

**Comment by MikeYermolayev** [comment]
@smcenlly hi, I'm still experiencing the issue on v1.0.994
Can't update any inline snapshots.

![image](https://user-images.githubusercontent.com/8783498/101348015-02534f80-389c-11eb-87d8-dd414965dd24.png)


here is my tsconfig. 
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "strict": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "outDir": "dist",
    "sourceMap": true
  },
  "include": ["./src/**/*"]
}
```

jest.config.ts:
```
module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    coverageThreshold: {
        global: {
            lines: 90,
            statements: 90,
            functions: 90,
            branches: 80,
        },
    },
    testMatch: ['**/*.test.ts'],
    setupFilesAfterEnv: ['./tests/jest.setup.ts'],
    collectCoverageFrom: [
        `**/src/**/*.ts`,
        `!**/src/server.ts`,
        `!**/src/typings/**`,
    ],
    coverageReporters: ['text', 'cobertura'],
};
```

Wallaby is auto-configured. 

Diagnostics report
```
{
  editorVersion: '1.51.1',
  pluginVersion: '1.0.251',
  editorType: 'VSCode',
  osVersion: 'darwin 19.6.0',
  nodeVersion: 'v14.15.0',
  coreVersion: '1.0.994',
  checksum: 'ZDcwNTI2ZTExNDU5NmY3MWYyYjlmYmZjODkwMjBlMzIsMTYwODE2MzIwMDAwMCwx',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/6w/plcs74fd5495c4pk48pgxyj40000gr/T/jest_e0',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<rootDir>',
              dependencyExtractor: undefined,
              detectLeaks: undefined,
              detectOpenHandles: undefined,
              displayName: undefined,
              errorOnDeprecated: false,
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'json', 'jsx', 'ts', 'tsx', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '170ae22dbc371244b81b1ae671adfb19',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<rootDir>',
              roots: [ '<rootDir>' ],
              runner: 'jest-runner',
              setupFiles: [],
              setupFilesAfterEnv: [ '<rootDir>/tests/jest.setup.ts' ],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<rootDir>/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/*.test.ts' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<rootDir>/node_modules/jest-jasmine2/build/index.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '^.+\\.tsx?$', '<rootDir>/node_modules/ts-jest/dist/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [ '**/src/**/*.ts', '!**/src/server.ts', '!**/src/typings/**' ],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<rootDir>/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'text', 'cobertura' ],
            coverageThreshold: { global: { lines: 90, statements: 90, functions: 90, branches: 80 } },
            detectLeaks: undefined,
            detectOpenHandles: undefined,
            enabledTestsMap: undefined,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: undefined,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 11,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: undefined,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<rootDir>',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<rootDir>/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|/\\..+/' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|/\\..+/' ],
            testMatch: [ '**/*.test.ts' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [ '**/src/**/*.ts', '!**/src/server.ts', '!**/src/typings/**' ],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/*.test.ts', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '**/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP <a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FSSWs01FppT6lGmARcX%2Fgiphy-downsized-medium.gif&token=ignore" data-gitmeme-token="ignore"><img src="https://media2.giphy.com/media/SSWs01FppT6lGmARcX/giphy-downsized-medium.gif" title="Created by gitme.me with /ignore"/></a> coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP <a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FSSWs01FppT6lGmARcX%2Fgiphy-downsized-medium.gif&token=ignore" data-gitmeme-token="ignore"><img src="https://media2.giphy.com/media/SSWs01FppT6lGmARcX/giphy-downsized-medium.gif" title="Created by gitme.me with /ignore"/></a> file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '/usr/local/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#-147406061'
  },
  packageJSON: {
    dependencies: {
      '@vizydrop/correlation-id': '4.0.0',
      '@vizydrop/logger': '1.9.3',
      cheerio: '0.22.0',
      'date-fns': '2.16.1',
      emojilib: '2.4.0',
      envalid: '6.0.2',
      got: '11.8.0',
      koa: '2.13.0',
      'koa-body': '4.2.0',
      'koa-router': '10.0.0',
      'koa-send': '5.0.1',
      lodash: '4.17.20',
      'p-throttle': '3.1.0',
      uuid: '8.3.1'
    },
    devDependencies: {
      '@types/cheerio': '0.22.22',
      '@types/jest': '26.0.15',
      '@types/koa': '2.11.6',
      '@types/koa-router': '7.4.1',
      '@types/koa-send': '4.1.2',
      '@types/lodash': '4.14.165',
      '@types/node': '14.14.9',
      '@typescript-eslint/eslint-plugin': '4.8.1',
      '@typescript-eslint/parser': '4.8.1',
      eslint: '7.13.0',
      'eslint-config-prettier': '6.15.0',
      'eslint-plugin-jest': '24.1.3',
      'eslint-plugin-node': '11.1.0',
      husky: '>=4',
      jest: '26.6.3',
      'jest-junit': '12.0.0',
      'lint-staged': '>=10',
      nock: '13.0.5',
      prettier: '2.2.0',
      'ts-jest': '26.4.4',
      'tsc-watch': '4.2.9',
      typescript: '4.1.2'
    }
  },
  fs: { numberOfFiles: 64 },
  debug: [
    '2020-12-07T11:53:40.502Z angular/cli config Angular CLI not found.\n',
    '2020-12-07T11:53:40.676Z jest/config Detected Jest.\n',
    '2020-12-07T11:53:40.677Z jest/config Configured Jest.\n',
    '2020-12-07T11:53:40.678Z project Wallaby Node version: v14.15.0\n',
    '2020-12-07T11:53:40.678Z project Wallaby config: <rootDir>/auto.detect\n',
    '2020-12-07T11:53:41.627Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.251/projects/1f0da1ead9c29f44\n',
    '2020-12-07T11:53:41.646Z uiService Listening port 51235\n',
    '2020-12-07T11:53:41.663Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2020-12-07T11:53:41.664Z workers Starting run worker instance #0\n',
    '2020-12-07T11:53:41.664Z workers Starting run worker instance #1\n',
    '2020-12-07T11:53:41.664Z workers Starting run worker instance #2\n',
    '2020-12-07T11:53:41.664Z workers Starting run worker instance #3\n',
    '2020-12-07T11:53:41.664Z workers Starting run worker instance #4\n',
    '2020-12-07T11:53:41.664Z workers Starting run worker instance #5\n',
    '2020-12-07T11:53:41.664Z workers Starting run worker instance #6\n',
    '2020-12-07T11:53:41.664Z workers Starting run worker instance #7\n',
    '2020-12-07T11:53:41.664Z workers Starting run worker instance #8\n',
    '2020-12-07T11:53:41.664Z workers Starting run worker instance #9\n',
    '2020-12-07T11:53:41.665Z workers Web server is listening at 49688\n',
    '2020-12-07T11:53:41.729Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-12-07T11:53:41.814Z project Stopping process pool\n',
    '2020-12-07T11:53:41.816Z project Test run started; run priority: 3\n',
    '2020-12-07T11:53:41.818Z project Running all tests\n',
    '2020-12-07T11:53:41.821Z workers Starting test run, priority: 3\n',
    '2020-12-07T11:53:41.821Z workers Distributing tests between 10 workers\n',
    '2020-12-07T11:53:41.822Z workers Running tests in parallel\n',
    '2020-12-07T11:53:41.822Z nodeRunner Starting sandbox [worker #0, session #0205u]\n',
    '2020-12-07T11:53:41.822Z nodeRunner Starting sandbox [worker #1, session #5s9e2]\n',
    '2020-12-07T11:53:41.822Z nodeRunner Starting sandbox [worker #2, session #mmhk9]\n',
    '2020-12-07T11:53:41.822Z nodeRunner Starting sandbox [worker #3, session #lkwet]\n',
    '2020-12-07T11:53:41.822Z nodeRunner Starting sandbox [worker #4, session #5ap7k]\n',
    '2020-12-07T11:53:41.822Z nodeRunner Starting sandbox [worker #5, session #330l0]\n',
    '2020-12-07T11:53:41.823Z nodeRunner Preparing sandbox [worker #0, session #0205u]\n',
    '2020-12-07T11:53:41.823Z nodeRunner Preparing sandbox [worker #1, session #5s9e2]\n',
    '2020-12-07T11:53:41.823Z nodeRunner Preparing sandbox [worker #2, session #mmhk9]\n',
    '2020-12-07T11:53:41.823Z nodeRunner Preparing sandbox [worker #3, session #lkwet]\n',
    '2020-12-07T11:53:41.823Z nodeRunner Preparing sandbox [worker #4, session #5ap7k]\n',
    '2020-12-07T11:53:41.823Z nodeRunner Preparing sandbox [worker #5, session #330l0]\n',
    '2020-12-07T11:53:42.075Z workers Started run worker instance (delayed) #0\n',
    '2020-12-07T11:53:42.075Z nodeRunner Prepared sandbox [worker #0, session #0205u]\n',
    '2020-12-07T11:53:42.076Z workers [worker #0, session #0205u] Running tests in sandbox\n',
    '2020-12-07T11:53:42.167Z workers Started run worker instance (delayed) #2\n',
    '2020-12-07T11:53:42.168Z nodeRunner Prepared sandbox [worker #2, session #mmhk9]\n',
    '2020-12-07T11:53:42.168Z workers [worker #2, session #mmhk9] Running tests in sandbox\n',
    '2020-12-07T11:53:42.168Z workers Started run worker instance (delayed) #6\n',
    '2020-12-07T11:53:42.173Z workers Started run worker instance (delayed) #1\n',
    '2020-12-07T11:53:42.173Z nodeRunner Prepared sandbox [worker #1, session #5s9e2]\n',
    '2020-12-07T11:53:42.173Z workers [worker #1, session #5s9e2] Running tests in sandbox\n',
    '2020-12-07T11:53:42.186Z workers Started run worker instance (delayed) #8\n',
    '2020-12-07T11:53:42.203Z workers Started run worker instance (delayed) #7\n',
    '2020-12-07T11:53:42.208Z workers Started run worker instance (delayed) #3\n',
    '2020-12-07T11:53:42.208Z nodeRunner Prepared sandbox [worker #3, session #lkwet]\n',
    '2020-12-07T11:53:42.208Z workers [worker #3, session #lkwet] Running tests in sandbox\n',
    '2020-12-07T11:53:42.209Z workers Started run worker instance (delayed) #5\n',
    '2020-12-07T11:53:42.209Z nodeRunner Prepared sandbox [worker #5, session #330l0]\n',
    '2020-12-07T11:53:42.209Z workers [worker #5, session #330l0] Running tests in sandbox\n',
    '2020-12-07T11:53:42.228Z workers Started run worker instance (delayed) #9\n',
    '2020-12-07T11:53:42.228Z workers Started run worker instance (delayed) #4\n',
    '2020-12-07T11:53:42.229Z nodeRunner Prepared sandbox [worker #4, session #5ap7k]\n',
    '2020-12-07T11:53:42.229Z workers [worker #4, session #5ap7k] Running tests in sandbox\n',
    '2020-12-07T11:53:55.121Z workers [5s9e2] Loaded unknown number of test(s)\n',
    '2020-12-07T11:53:55.122Z workers [5s9e2] Test executed: should get status\n',
    '2020-12-07T11:53:55.133Z workers [5s9e2] Run 1 test(s), skipped 0 test(s)\n',
    '2020-12-07T11:53:55.134Z workers [5s9e2] Sandbox is responsive, closing it\n',
    '2020-12-07T11:53:55.254Z workers [5ap7k] Loaded unknown number of test(s)\n',
    '2020-12-07T11:53:55.271Z workers [5ap7k] Test executed: should get account\n',
    '2020-12-07T11:53:55.276Z workers [lkwet] Loaded unknown number of test(s)\n',
    '2020-12-07T11:53:55.282Z workers [lkwet] Test executed: should get schema for requested types\n',
    '2020-12-07T11:53:55.289Z workers [mmhk9] Loaded unknown number of test(s)\n',
    '2020-12-07T11:53:55.292Z workers [mmhk9] Test executed: should get connector config\n',
    '2020-12-07T11:53:55.295Z workers [5ap7k] Test executed: should use system user as default\n',
    '2020-12-07T11:53:55.301Z workers [0205u] Loaded unknown number of test(s)\n',
    '2020-12-07T11:53:55.302Z workers [lkwet] Run 1 test(s), skipped 0 test(s)\n',
    '2020-12-07T11:53:55.304Z workers [lkwet] Sandbox is responsive, closing it\n',
    '2020-12-07T11:53:55.309Z workers [mmhk9] Run 1 test(s), skipped 0 test(s)\n',
    '2020-12-07T11:53:55.311Z workers [mmhk9] Sandbox is responsive, closing it\n',
    '2020-12-07T11:53:55.340Z workers [5ap7k] Test executed: should return handle wrong creds\n',
    '2020-12-07T11:53:55.350Z workers [5ap7k] Run 3 test(s), skipped 0 test(s)\n',
    '2020-12-07T11:53:55.352Z workers [5ap7k] Sandbox is responsive, closing it\n',
    '2020-12-07T11:53:55.353Z workers [0205u] Test executed: should respond with 200\n',
    '2020-12-07T11:53:55.366Z workers [0205u] Run 1 test(s), skipped 0 test(s)\n',
    '2020-12-07T11:53:55.367Z workers [0205u] Sandbox is responsive, closing it\n',
    '2020-12-07T11:53:55.480Z workers [330l0] Loaded unknown number of test(s)\n',
    '2020-12-07T11:53:55.481Z workers [330l0] Test executed: should respond with 200\n',
    '2020-12-07T11:53:55.491Z workers [330l0] Run 1 test(s), skipped 0 test(s)\n',
    '2020-12-07T11:53:55.492Z workers [330l0] Sandbox is responsive, closing it\n',
    '2020-12-07T11:53:55.492Z workers Merging parallel test run results\n',
    '2020-12-07T11:53:55.496Z project Test run finished\n',
    '2020-12-07T11:53:55.496Z project Processed console.log entries\n',
    '2020-12-07T11:53:55.497Z project Processed loading sequences\n',
    '2020-12-07T11:53:55.497Z project Processed executed tests\n',
    '2020-12-07T11:53:55.500Z project Processed code coverage\n',
    '2020-12-07T11:53:55.522Z project Test run result processed and sent to IDE\n',
    '2020-12-07T11:54:09.932Z fs File changed in editor: tests/syncSchema.test.ts\n',
    '2020-12-07T11:54:09.938Z project Test run started; run priority: 2\n',
    '2020-12-07T11:54:09.938Z testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-12-07T11:54:09.940Z workers Starting test run, priority: 2\n',
    '2020-12-07T11:54:09.940Z nodeRunner Starting sandbox [worker #0, session #gq3ch]\n',
    '2020-12-07T11:54:09.940Z nodeRunner Preparing sandbox [worker #0, session #gq3ch]\n',
    '2020-12-07T11:54:09.940Z nodeRunner Prepared sandbox [worker #0, session #gq3ch]\n',
    '2020-12-07T11:54:09.940Z workers [worker #0, session #gq3ch] Running tests in sandbox\n',
    '2020-12-07T11:54:10.443Z fs File changed: tests/__snapshots__/syncSchema.test.ts.snap\n',
    '2020-12-07T11:54:10.858Z fs File changed: tests/syncSchema.test.ts\n',
    '2020-12-07T11:54:10.859Z fs No changes detected for tests/syncSchema.test.ts\n',
    '2020-12-07T11:54:10.859Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-12-07T11:54:10.893Z workers [gq3ch] Loaded unknown number of test(s)\n',
    '2020-12-07T11:54:10.893Z workers [gq3ch] Test executed: should get schema for requested types\n',
    '2020-12-07T11:54:10.896Z workers Sandbox (active) [gq3ch] error: undefined\n',
    '2020-12-07T11:54:10.904Z workers [gq3ch] Sandbox is responsive, closing it\n',
    '2020-12-07T11:54:10.905Z project Test run finished\n',
    '2020-12-07T11:54:10.910Z project Changes did not trigger any tests\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
@MikeYermolayev Thanks for the report. The latest Jest inline snapshot package version compatibility issue is fixed and the fix is available in [the latest Wallaby core v1.0.995](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by MikeYermolayev** [comment]
Wow, that was fast🤘🏻
It works

**Comment by kirillgroshkov** [comment]
What helped for me with Jest 27 and typescript is to add `sourceMap: true` in my `tsconfig.json`. It immediately fixed the problem.

`ts-jest` used to have it on by default, but changed it in v27.

**Comment by smcenlly** [comment]
@kirillgroshkov

> What helped for me with Jest 27 and typescript is to add sourceMap: true in my tsconfig.json

Thanks for letting us know about this. Out of interest, was `sourceMap: false` in your existing `tsconfig.json` or was it missing?

**Comment by kirillgroshkov** [comment]
> Thanks for letting us know about this. Out of interest, was `sourceMap: false` in your existing `tsconfig.json` or was it missing?

Default is, I believe, `false`

**Comment by smcenlly** [comment]
Thanks - we have reviewed the `ts-jest` change and it appears that source maps will **only** be disabled if sourceMap is explicitly set in the `tsconfig.json` with a value of false. By default, if the `sourceMap` property is omitted, TypeScript will not emit source maps but `ts-jest` will.
