### ISSUE TITLE
Wallaby test should fail

### ISSUE THREAD

**Issue by seaBubble** [wallabyjs/public#2063]
### Issue description or question
I have a test for some Angular code that uses the rxjs pipe operator on the result of a function. If this function returns undefined, an error will be thrown: 'TypeError: Cannot read property 'pipe' of undefined'. When testing this code (test() called inside the constructor of the tested class), this causes the test in Karma to fail, but it passes in Wallabyjs.

Code:
```javascript
  private returnUndefined(): Observable<any> {
    return undefined;
  }

  // Function under test: passes in Wallaby
  private test(): Observable<any> {
    return this.returnUndefined().pipe(
      map(val => {
        return val;
      })
    );
  }
```
### Wallaby.js configuration file
Not relevant

### Code editor or IDE name and version
Not relevant

### OS name and version
Not relevant

**Comment by ArtemGovorov** [comment]
Unfortunately we can't reproduce the issue with your code:

<img width="750" alt="Screen Shot 2019-05-03 at 12 26 19 pm" src="https://user-images.githubusercontent.com/979966/57117344-add21f00-6d9e-11e9-9c99-4a64cddacaa3.png">


As you can see on the screenshot, Wallaby correctly displays failing test. I have created this sample repo branch https://github.com/wallabyjs/ngCliWebpackSample/blob/wallaby-2063/src/app/app.component.spec.ts with the code we have used. See if you can run the repo locally and get the correct result, and if so, please fork the repo to add a code sample that demonstrates the issue - we are happy to take a look.

**Comment by seaBubble** [comment]
Thanks for looking into this.
Sorry, I simplified my code to raise the issue and in the process I left out the important part.

If you try with this

```javascript
import { BehaviorSubject, combineLatest, Observable } from 'rxjs';
import { map, switchMap, take } from 'rxjs/operators';


const map = v => v;

class Test {
  a = new BehaviorSubject('a');
  b = new BehaviorSubject('b');
  
  constructor() {
    this.test().subscribe();
  }

  private returnUndefined(): Observable<any> {
    return undefined;
  }

  // Function under test: passes in Wallaby
  public test(): Observable<any> {
    return combineLatest(this.a, this.b).pipe(
      switchMap(([a, b]) => {
        return this.returnUndefined().pipe(
          map(val => {
            return val;
          })
        );
      })
    );
  }

}

it('issue 2063', () => {
  new Test()
});

```

You should then see the test passing.
It seems it is the combineLatest that causes it not to fail.

Thanks,

**Comment by ArtemGovorov** [comment]
Thanks for providing the additional details. The issue is fixed in [the latest Wallaby core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by seaBubble** [comment]
Thanks for fixing this so quickly.
I can see the TypeError now but the tests still doesn't appear as failing. Is this the expected behaviour?

**Comment by ArtemGovorov** [comment]
@seaBubble The test is not actually failing. Same in Karma - as you may see for your example the error is reported for `afterAll`. 

The reason is that your code doesn't produce any immediate error when the test is running. The error occurs after the test is finished running due to the async nature of your code and the sync nature of your test. When the test is executing, the `returnUndefined` is not called, it is called later (after test execution is finished).
