### ISSUE TITLE
Mocha custom UI extensions don't work with WallabyJS

### ISSUE THREAD

**Issue by devonhumes** [wallabyjs/public#2200]
### Issue description or question

We have extended the Mocha BDD UI to include custom methods on the `describe` and `it` objects (similar to `describe.only`). However, when running using WallabyJS and the custom UI the methods on the `describe` function are found, but the methods on the `it` function are not. Is there something that we are missing?

We are extending using the method defined in https://github.com/mochajs/mocha/wiki/Third-party-UIs. Our code is based off of the definitions used in the bdd UI file. The code for our extension methods is below.

### Wallaby.js configuration file

```javascript
// paste your config here

module.exports = function() {
    return {
        files: [
            { pattern: 'src/common/environment/environment.ts' },
            "src/**/*.ts"
        ],
        tests: [
            "tests/**/*.spec.ts"
        ],
        testFramework: 'mocha',
        env: {
            type: 'node',
        },
        setup: function(w) {
            const ui = require(path.resolve(process.cwd(), 'src/common/mocha/bdd'));
            w.testFramework.ui(ui);
        }
    }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.38.0
IntelliJ IDEA v2019.2

### OS name and version

OSX

### Extension code

```typescript

(Mocha as any).interfaces['xmd-integration-tests'] = xmdIntegrationTestsUi;


function xmdIntegrationTestsUi(suite: Suite) {
  const suites = [suite];

  suite.on(EVENT_FILE_PRE_REQUIRE, function(context, file, mocha) {
    const common = require('mocha/lib/interfaces/common')(suites, context, mocha);

    context.before = common.before;
    context.after = common.after;
    context.beforeEach = common.beforeEach;
    context.afterEach = common.afterEach;
    context.run = mocha.options.delay && common.runWithSuite(suite);
    /**
     * Describe a "suite" with the given `title`
     * and callback `fn` containing nested suites
     * and/or tests.
     */

    const describe = function (title: string, fn?: (this: Suite) => void): Suite {
      return common.suite.create({
        title: title,
        file: file,
        fn: fn
      } as any);
    };

    describe.only = function (title: string, fn?: (this: Suite) => void): Suite {
      return common.suite.only({
        title: title,
        file: file,
        fn: fn
      } as any);
    };

    describe.skip = function (
      title: string,
      fn?: (this: Suite) => void
    ) {
      return common.suite.skip({
        title: title,
        file: file,
        fn: fn
      } as any);
    }
    /******************************************************************
     * Extension methods
     ******************************************************************/;

    describe.beta = () => {
    }; // Additional function
    // ... Additional extension methods

    context.describe = context.context = describe;

    /**
     * Pending describe.
     */

    context.xdescribe = context.xcontext = describe.skip;

    /**
     * Describe a specification or test-case
     * with the given `title` and callback `fn`
     * acting as a thunk.
     */
    const it = function (title: string, fn?: AsyncFunc | Func): Test {
      const suite = suites[0];
      if (suite.isPending()) {
        fn = undefined;
      }
      const test = new Test(title, fn);
      test.file = file;
      suite.addTest(test);
      return test;
    } as any;

    it.only = function (title: string, fn?: Func | AsyncFunc) {
      return common.test.only(mocha, context.it(title, fn));
    } as any;

    it.skip = function (title: string) {
      return context.it(title);
    } as any;

    it.retries = function (n: number) {
      (context as any).retries(n);
    };

    /******************************************************************
     * Extension methods
     ******************************************************************/
    it.beta = () => {}; // Additional function
    // ... Additional extension methods

    context.it = context.specify = it;

    /**
     * Pending test case.
     */

    context.xit = context.xspecify = it.skip;

}

export = xmdIntegrationTestsUi;

````

**Comment by ArtemGovorov** [comment]
Thanks for the report. There was an issue with our integration with mocha that is now fixed and published in [the latest Wallaby core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). Please forcing the update to the latest core and the issue should be resolved for you.

**Comment by devonhumes** [comment]
I'm on the latest version of the WallabyJS core in both Visual Studio code
and IntelliJ and I still see the issue. It reports that `it.value` is not a
function.

**Comment by devonhumes** [comment]
My core version number is ```wallaby.js started
core v1.0.732```

**Comment by ArtemGovorov** [comment]
I have created this sample repo https://github.com/ArtemGovorov/wallaby-2200, with your config, a simple test and [simple interface that adds `beta` function to `it`](https://github.com/ArtemGovorov/wallaby-2200/blob/master/src/common/mocha/bdd.ts#L15).

When I run Wallaby on it, I can see the `beta` function is present on the `it` function:

<img width="334" alt="Screen Shot 2019-09-08 at 4 06 03 pm" src="https://user-images.githubusercontent.com/979966/64484260-edc87780-d252-11e9-95d9-700acfd18a68.png">

Could you please try cloning the repo and running it to see if it is working for you?

**Comment by ArtemGovorov** [comment]
My apologies, the commit with the fix didn't make it into 1.0.732. Please force update to [the latest core 1.0.733](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), and the issue should be resolved.
