### ISSUE TITLE
Buffer() DeprecationWarning

### ISSUE THREAD

**Issue by dnicolson** [wallabyjs/public#2262]
When running an extension there is a DeprecationWarning that is logged to the debug console. 

Clicking `warning.js` results in an error, this is probably a VS Code issue though.

![Screen Shot 2019-11-06 at 14 46 08](https://user-images.githubusercontent.com/2276355/68304027-41b1da00-00a5-11ea-9756-93df4b55a5ec.png)

**Comment by smcenlly** [comment]
Thanks for reporting the warning messages. We've fixed the deprecation warnings in the latest version of Wallaby. You'll see in the developer console that `warning.js` is from vscode as you suggested and is unrelated to Wallaby.

**Comment by dnicolson** [comment]
Unfortunately, there is still an issue when running the extension. There are instances of `new Buffer()` in version [1.0.263](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/WallabyJs/vsextensions/wallaby-vscode/1.0.263/vspackage) of the VS Code extension.

The problematic line is `return new Buffer(e,"base64").toString().split("\n")[2]`, the warning does not appear when replacing that with `Buffer.fom()` in the `dist/index.js` file.

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of Wallaby (**Wallaby for VS Code v1.0.264**, and **Wallaby core version v1.0.1029**).
