### ISSUE TITLE
Performance issues in VSCode

### ISSUE THREAD

**Issue by punshonjm** [wallabyjs/public#2426]
### Issue description

Since a recent registering a license (it updated core after I registered), Wallaby has begun to struggle to perform well to the point that it is causing delays while typing. Did not have this issue while using the trial version except if wallaby was running inside several projects at once. Which calling stop on the ones i wasnt actively testing would help

Tried disabling GPU rendering, sort of works better but chugs the entire machine
Disabled all other extensions still struggles 

Running on MBP 2019 2.6Ghz/6core/i7/16gb/RadeonPro4GB
Not running excessive amount of other software, so plenty of RAM/CPU to spare

Keen to figure out why

It seemed to start after VSCode April update (with mentions faster syntax highlighting, so thought potentially related)
Tried downgrading to the March update version, same issue persists but seems to work a little better but not much. 

I can see in the Process Explorer in VSCode that the wallaby.js is spining up a lot of sub-processes as I type. 

![Screen Shot 2020-05-28 at 9 50 55 am](https://user-images.githubusercontent.com/9315568/83083204-e12dcd00-a0c8-11ea-9649-acd144824020.png)

### Wallaby diagnostics report

[Diagnostics Report.txt](https://github.com/wallabyjs/public/files/4692632/Diagnostics.Report.txt)

Edit:
Remove more repeated row

Repeats steps after '2020-05-27T03:00:44.612Z workers Starting run worker instance #0\n', over and over

**Comment by smcenlly** [comment]
We've been able to reproduce similar behavior to what you're seeing using Jest v25 with `automatic configuration`. We're not entirely sure what's going on yet but our team is investigating and we'll get back to you when we know more about what's going on or have a fix.

**Comment by punshonjm** [comment]
Thanks, happy to provide additional info or try out changes if necessary! Do you know if there is manual options I can set to 'bandaid' the issue in the meantime?

**Comment by smcenlly** [comment]
I'm not sure whether this will work for you, but we have a couple of things you could try as a short-term workaround:

**1. Reduce your worker parameters**
You can do this by creating a configuration file, or by editing your package.json file.

`package.json`
```
...
  "wallaby": {
    "workers": {
      "initial": 2,
      "regular": 2
    }
  }
...
```

`wallaby.js` configuration file
```
module.exports = () => ({
   autoDetect: true,
   workers: {
     initial: 6,
     regular: 2
   }
});
```

**2. Use the [delay setting](https://wallabyjs.com/docs/config/overview.html#delays-setting)**
Try changing the `delays: run` setting to 1500ms between executions. As above, you may set in `package.json` or by creating a `wallaby.js` configuration file.

`package.json`
```
...
  "wallaby": {
    "delays": {
      "run": 1500
    }
  }
...
```

**Comment by punshonjm** [comment]
Thank you, will have a play with these options and see how it goes.

**Comment by punshonjm** [comment]
The suggested settings above helped get it working without destroying VSCode, thank you! TO get actual feedback, I had to tweak workers to be initial & regular set as 4 and remove the delay. Otherwise, I just ended up getting no info at all. 

Thanks for the suggestion! Looking forward to hearing more about getting back to auto when your team has had a chance to have a look

**Comment by smcenlly** [comment]
Thanks for letting us know. We have been working on this for the entire day and have a much better understanding about what's going on. 

When Wallaby starts, it creates a number of worker processes to distribute and run your tests. When you make a file change, Wallaby recycles the existing process (because creating a new process is expensive). Before we recycle the process, we perform a health-check by performing a network PING. In your case, Wallaby is getting no response and decides to recycle the process. Because you have a pending test run, Wallaby then starts everything up again and can have the same problem again when you start typing. 

The cause of the issue is that jest's transform, module loading, and global setup code is all synchronous and is blocking node.js event loop, including our health check. What is also interesting is that this only happens when a test is first transformed/executed on one of the worker processes. Unfortunately, after initial startup, Wallaby distributes the tests randomly to different worker processes, so it's quite likely that you'll run into the problem if your transform, module loading, global setup takes more than 1 second to execute for the first time.

If you have the time/patience, you can also "fix" the problem temporarily by only typing 1 keystroke every 2 seconds for 5-10 times. After that point, all the tests have been loaded across all worker processes and everything always works.

We are working on the implementation of the fix which should be available later today or tomorrow, at which point you will be able to remove the settings we suggested.

**Comment by smcenlly** [comment]
We've finished making the changes to address your problem. The fix is available in the latest version of Wallaby core, v1.0.900. Wallaby should update automatically for you within a few minutes, but if it does not, please open your editor and launch the Command Palette using `Ctrl/Cmd + Shift + P`, then run the command `Wallaby.js: Force Core Update`. Please note that Wallaby must be stopped for the update to be applied.

The fix still includes some timeout settings, but these are now different for initial vs. subsequent test runs for a given worker process. We have tuned the timeouts based on the projects we used to replicate your problem, but if you are still seeing problems after the update, please let us know as we may need to work with you to tune these settings for your project.

**Comment by punshonjm** [comment]
Just an update to this, performance still not what it was however it is doing much better. I've found changing the my package.json to add the below helps performance. Its more noticeable on larger projects. For example, large Expresss.js servers feels like its redoing all tests (that use the express app anywhere) while working on a single endpoints underlying functions.

```
"wallaby": {
    "runMode": "onsave"
  }
```

**Comment by ArtemGovorov** [comment]
> For example, large Expresss.js servers feels like its redoing all tests (that use the express app anywhere) while working on a single endpoints underlying functions

Can you try running Jest CLI in watch mode, make some changes (those when done in Wallaby feels like its redoing all tests) to see if Jest in watch mode is doing the same?

**Comment by ArtemGovorov** [comment]
> For example, large Expresss.js servers feels like its redoing all tests (that use the express app anywhere) while working on a single endpoints underlying functions.

There are a couple of things you may try (apart from investigating why single endpoint file editing affects many/all of your test files):

- Use [exclusive test runs](https://wallabyjs.com/docs/intro/get-started-vscode.html#test-focusing) or [test file selection via code comment](https://wallabyjs.com/docs/intro/selected-tests.html#test-file-selection), when you are anticipating that your changes are mostly affecting few test files that need to run (when required, you can always switch to a full test run).

- Configure Wallaby to ignore file loading dependencies (and only use test runtime dependencies between your test and source files). This may help somewhat, however there may be [some implications](https://github.com/wallabyjs/public/issues/1444#issuecomment-354199248). You may add the setting under wallaby section in your package.json:

```
{
  …
  "wallaby": {"ignoreFileLoadingDependencyTracking": true}
}
```

**Comment by punshonjm** [comment]
> > For example, large Expresss.js servers feels like its redoing all tests (that use the express app anywhere) while working on a single endpoints underlying functions
> 
> Can you try running Jest CLI in watch mode, make some changes (those when done in Wallaby feels like its redoing all tests) to see if Jest in watch mode is doing the same?

Just tried this out and Jest in watch mode was running through all tests after making a change to one file. Changed 1 file and watch ran 133 tests, though probably more because watch restarted the test run a couple times.

> "wallaby": {"ignoreFileLoadingDependencyTracking": true}

I'll try this out and see how I go. Thanks
