### ISSUE TITLE
Wallaby seems to forget in which timezone setting it must be running

### ISSUE THREAD

**Issue by ekaradon** [wallabyjs/public#2550]
### Issue description or question

I've setup the timezone for wallaby through a file named `global-setup.js` with the following content: 
```javascript
module.exports = async() => {
    process.env.TZ = 'UTC';
};
```
And referenced within `package.json` like so:
```json
  "jest": {
    "globalSetup": "./global-setup.js"
  }
```
And it works well, at first. However, as I'm editing/modifying more and more tests and stuff, I see some tests (not modified in any way) failing. And it's always because it seems that the local timezone is preferred to the timezone initially set. 
If I then restart wallaby it works again until it does not anymore. The duration during which it will be retained and the reason why it is forgotten eludes me.

Is there some stuff that I should do in order to set this definitely for Wallaby? By the way, I never have this problem with the jest runner...

**Comment by smcenlly** [comment]
Thanks for reporting your problem. We identified a problem when Wallaby restarts its node worker processes when running jest and you have set a `process.env` variable in your `globalSetup` function.

This is fixed in the latest version of Wallaby core, v1.0.981. Wallaby should update for you automatically but if it does not, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by ThomasGHenry** [comment]
I cannot for the life of me get TZ to stick. Is there doc on this? Feels like it's still broken. Did this ever work for you, @ekaradon ? Thanks, all!

**Comment by ThomasGHenry** [comment]
@smcenlly, what would be the Wallaby way to ensure this always passes? (Jest and CRA in this case)

```
describe('Timezones', () => {
  it('should always be UTC', () => {
    expect(new Date().getTimezoneOffset()).toBe(0);
  });
});
```

Thanks!

**Comment by ThomasGHenry** [comment]
<img width="808" alt="Screen Shot 2022-06-28 at 15 00 54" src="https://user-images.githubusercontent.com/97537/176251437-9e2c5009-d335-444b-8942-a395878d41b6.png">
<img width="451" alt="Screen Shot 2022-06-28 at 15 00 30" src="https://user-images.githubusercontent.com/97537/176251444-3bf14f96-a4a1-4da6-91bf-ad5e6c3d9b17.png">

**Comment by smcenlly** [comment]
You should be able to configure jest to do this and Wallaby will also work for you. We just tried the steps in this [stack overflow article](https://stackoverflow.com/questions/56261381/how-do-i-set-a-timezone-in-my-jest-config) and it works for us:

**1. Add this to your package.json**
```javascript
  "jest": {
     ...
     // depending on your paths it can also be './global-setup.js' 
    "globalSetup": "../global-setup.js"
  }
}
```

**2. Put this file besides package.json as global-setup.js**
```javascript
module.exports = async () => {
    process.env.TZ = 'UTC';
};
```

**3. Optional: Add a test that ensures UTC execution**

```javascript
describe('Timezones', () => {
    it('should always be UTC', () => {
        expect(new Date().getTimezoneOffset()).toBe(0);
    });
});
```

---

If you're still having problems, please provide a sample repo and your diagnostics report in a [new issue](https://github.com/wallabyjs/public/issues/new/choose). We'd be happy to take a look for you.
