### ISSUE TITLE
Angular component not resolved, problem with templateUrl ?

### ISSUE THREAD

**Issue by GarfieldDeepClone** [wallabyjs/public#2553]
### Issue description or question

I'm trying to test an Angular component:
```
@Component({
	selector: 'asset-overview',
	templateUrl: './asset-overview.component.html',
	styleUrls: ['./asset-overview.component.scss']
})
```
which includes another component -> FilterComponent
and I'm getting this error message:
`Error: Component 'FilterComponent' is not resolved:
	 - templateUrl: ./filter.component.html
	Did you run and wait for 'resolveComponentResources()'?`

It works with karma. Any idea what is maybe wrong with the wallaby config I have?

### Wallaby diagnostics report
[wallaby_diagnostics.txt](https://github.com/wallabyjs/public/files/5478613/wallaby_diagnostics.txt)

**Comment by smcenlly** [comment]
It looks like you have a custom angular project that doesn't use a common template/pattern (e.g. is not created by Angular CLI). We'll need a bit more information from you in order to understand why it's not working for you, but we do have some suggestions we can provide:

1. Please try our [new (built-in) Webpack integration](https://wallabyjs.com/blog/new-webpack-integration.html) instead of using the `wallaby-webpack` package. The key difference is that the new built-in postprocessor integrates with webpack’s loaders to perform instrumentation which allows you to use the same loaders as you use in your test, development and production webpack configurations (such as babel-loader for ES6/ES7/ES8, ts-loader or awesome-typescript-loader for TypeScript and coffee-loader for CoffeeScript). This means less configuration and less customization of your Wallaby configuration. You can read more in [our docs](https://wallabyjs.com/docs/integration/webpack-built-in.html). By updating to use the new webpack configuration, Wallaby should be running the same as your tests are running when they are bundled with webpack.

2. If you want to try and get your configuration working with the open source wallaby-webpack package, then please compare your configuration against our [most recent Angular CLI configuration file](https://wallabyjs.com/docs/integration/angular.html#manual-configuration-wallabyjs-file). Specifically, try aligning the **compilers**, **preprocessors**, **middleware** and **postprocessor** sections. The webpack overrides that exist in _our_ configuration file are also important so it may be worth trying to replace what you have with what we have in our configuration. Without knowing your babel configuration, we expect that the cause of your problem is that you are using babel to compile your TypeScript files instead of TypeScript and then `getCustomTransformers` is not running as it does in our Angular configuration file.

---

If you prefer, or are still having problems after trying the above, can you please add a minimal set of files to https://github.com/wallabyjs/wallaby2553/ so that we can duplicate your problem (we have given you access to this repo). It will be important to make sure that the tests are passing from the command line outside of wallaby. We expect you'll need to provide:

* tsconfig.json
* babel configuration file(s)
* webpack configuration file(s)

From what you have reported, you should not need to provide us with any of your production code to reproduce the issue (configuration and a single dummy test should be enough).

**Comment by GarfieldDeepClone** [comment]
[webpack config files.zip](https://github.com/wallabyjs/public/files/5487395/webpack.config.files.zip)

**Comment by NikGovorov** [comment]
Could you please also share you karma config file?

**Comment by GarfieldDeepClone** [comment]
Attached.

**Comment by smcenlly** [comment]
Thanks for providing your configuration files. There were a couple of edge cases in your configuration that Wallaby's webpack integration was not able to handle (your specific html configuration, and your use of `thread-loader`).

The latest version of Wallaby, `v1.0.984`, should now work with your configuration. We have updated the [sample repo we created for this issue](https://github.com/wallabyjs/wallaby2553/) with a working configuration:

**wallaby.js configuration**
```javascript
const options = require('./webpack.dev')({ isTest: true });

module.exports = function (wallaby) {
  return {
    // set `load: false` to all source files and tests processed by webpack
    // (except external files),
    // as they should not be loaded in browser,
    // their wrapped versions will be loaded instead
    files: [
      { pattern: 'src/**/*.js', load: false },
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'src/**/*.html', load: false },
      { pattern: 'webpack-config/*.js', load: false },
      { pattern: 'test/karma/helpers.js', load: false },
      { pattern: 'test/karma/runtimeError.js', load: false },
      { pattern: 'test/karma/simulateMaskedRuntimeError.js', load: false },

      // ignore test files since they get declared in the "tests" option
      { pattern: 'src/**/test/e2e/**/*.{js,ts}', ignore: true },
      { pattern: 'src/**/test/midway/**/*.{js,ts}', ignore: true },
      { pattern: 'src/**/test/unit/**/*.helpers.{js,ts}', ignore: true },
      { pattern: 'src/**/*.spec.ts', ignore: true },
    ],

    tests: [
      { pattern: 'src/**/test/unit/**/!(*.helpers).{js,ts}', load: false },
      { pattern: 'src/**/*.spec.ts', load: false },
    ],

    postprocessor: wallaby.postprocessors.webpack(options),

    setup: function () {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    },
  };
};
```

**Comment by GarfieldDeepClone** [comment]
Thank you :)

So it seems the only problem was this line?
`webpackConfig.resolve.extensions = ['.js', '.json'];`

Everything else I had configured the same way as you did in wallaby.js

**Comment by smcenlly** [comment]
The problem was not your configuration, the issues/edge cases were in Wallaby's webpack integration which we fixed version `v1.0.984`. You should not have needed to change your configuration after Wallaby updated to the latest version.

**Comment by GarfieldDeepClone** [comment]
You mean the original problem?
Error: Component 'FilterComponent' is not resolved

is now fixed in v.1.0.984?

**Comment by smcenlly** [comment]
Yes - the original problem should now be fixed in v1.0.984+.
