### ISSUE TITLE
Debugging Jest unit tests with mobx proxies and displayed values

### ISSUE THREAD

**Issue by vjau** [wallabyjs/public#2873]
### Issue description or question
I have trouble using Wallaby with a Mobx project. Mobx is a state management library that allow you to observe some data change wrapping the data with a proxy. 
When the tests are red, instead of seeing the actual (wrong) output under Wallaby, i see the proxy. 
Running the same test with the same configuration under Jest without Wallaby gives me the actual output and not the proxy.
Also, using the wallaby debugger and peeking at values, i see the proxy and not the values. 

Repro demonstrating the issue :
https://github.com/vjau/bugmobxwallaby

### Wallaby diagnostics report

```
{
  editorVersion: 'WebStorm 2021.2.3',
  pluginVersion: '1.0.227',
  editorType: 'IntelliJ',
  osVersion: 'linux 5.4.0-91-generic',
  nodeVersion: 'v14.18.2',
  coreVersion: '1.0.1188',
  checksum: 'ZDAzNTY3MTg2N2YzNTAyMTI4YTcyNzhlNWVlZGYwZTMsMTY0OTgwODAwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/tmp/jest_rs',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/dev/temp/bugmobxwallaby',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'jsx', 'ts', 'tsx', 'json', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: 'a8a8f49cb708d661abb30344362a964d',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/dev/temp/bugmobxwallaby',
              roots: [ '<homeDir>/dev/temp/bugmobxwallaby' ],
              runner: '<homeDir>/dev/temp/bugmobxwallaby/node_modules/jest-runner/build/index.js',
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/dev/temp/bugmobxwallaby/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/tests/**/*.[jt]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/dev/temp/bugmobxwallaby/node_modules/jest-circus/runner.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '\\.[jt]sx?$', '<homeDir>/dev/temp/bugmobxwallaby/node_modules/babel-jest/build/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/dev/temp/bugmobxwallaby/coverage',
            coverageProvider: 'v8',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 7,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/dev/temp/bugmobxwallaby',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/dev/temp/bugmobxwallaby/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/tmp/jest_rs', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/tmp/jest_rs', '\\./coverage' ],
            testMatch: [ '**/tests/**/*.[jt]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//, ignore: true, trigger: true, load: true },
      { pattern: '/tmp/jest_rs', regexp: /\/tmp\/jest_rs/, ignore: true, trigger: true, load: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/tests/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '/tmp/jest_rs', regexp: /\/tmp\/jest_rs/, ignore: true, trigger: true, load: true, test: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true },
      { pattern: '**/tests/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '/usr/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#216304777'
  },
  packageJSON: {
    dependencies: { mobx: '^6.3.8' },
    devDependencies: {
      '@babel/core': '^7.16.0',
      '@babel/preset-env': '^7.16.4',
      '@babel/preset-typescript': '^7.16.0',
      '@types/jest': '^27.0.3',
      'babel-jest': '^27.3.1',
      jest: '^27.3.1',
      typescript: '^4.5.2'
    }
  },
  fs: { numberOfFiles: 8 },
  debug: [
    '2021-12-11T18:20:57.689Z angular/cli config Angular CLI not found.\n',
    '2021-12-11T18:20:57.790Z jest/config Detected Jest.\n',
    '2021-12-11T18:20:57.791Z jest/config Configured Jest.\n',
    '2021-12-11T18:20:57.792Z project Wallaby Node version: v14.18.2\n',
    '2021-12-11T18:20:57.792Z project Wallaby config: <homeDir>/dev/temp/bugmobxwallaby/auto.detect\n',
    '2021-12-11T18:20:57.848Z project File cache: <homeDir>/.cache/JetBrains/WebStorm2021.2/wallaby/projects/d21dddfc91d44844\n',
    '2021-12-11T18:20:57.855Z uiService Listening port 51236\n',
    '2021-12-11T18:20:57.861Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2021-12-11T18:20:57.861Z workers Starting run worker instance #0\n',
    '2021-12-11T18:20:57.861Z workers Starting run worker instance #1\n',
    '2021-12-11T18:20:57.861Z workers Starting run worker instance #2\n',
    '2021-12-11T18:20:57.861Z workers Starting run worker instance #3\n',
    '2021-12-11T18:20:57.861Z workers Starting run worker instance #4\n',
    '2021-12-11T18:20:57.861Z workers Starting run worker instance #5\n',
    '2021-12-11T18:20:57.862Z workers Web server is listening at 39317\n',
    '2021-12-11T18:20:57.894Z project Stopping process pool\n',
    '2021-12-11T18:20:57.894Z project File cache is up-to-date, starting full test run\n',
    '2021-12-11T18:20:57.896Z project Test run started; run priority: 3\n',
    '2021-12-11T18:20:57.897Z project Running all tests\n',
    '2021-12-11T18:20:57.899Z workers Starting test run, priority: 3\n',
    '2021-12-11T18:20:57.900Z nodeRunner Starting sandbox [worker #0, session #f9l7r]\n',
    '2021-12-11T18:20:57.900Z nodeRunner Preparing sandbox [worker #0, session #f9l7r]\n',
    '2021-12-11T18:20:58.038Z workers Started run worker instance (delayed) #3\n',
    '2021-12-11T18:20:58.038Z workers Started run worker instance (delayed) #1\n',
    '2021-12-11T18:20:58.052Z workers Started run worker instance (delayed) #0\n',
    '2021-12-11T18:20:58.053Z nodeRunner Prepared sandbox [worker #0, session #f9l7r]\n',
    '2021-12-11T18:20:58.053Z workers [worker #0, session #f9l7r] Running tests in sandbox\n',
    '2021-12-11T18:20:58.055Z workers Started run worker instance (delayed) #2\n',
    '2021-12-11T18:20:58.059Z workers Started run worker instance (delayed) #4\n',
    '2021-12-11T18:20:58.070Z workers Started run worker instance (delayed) #5\n',
    '2021-12-11T18:20:58.969Z workers Scheduling Jest Test Run (f9l7r): 2021-12-11T18:20:58.298Z\n',
    '2021-12-11T18:20:58.970Z workers [f9l7r] Loaded unknown number of test(s)\n',
    '2021-12-11T18:20:58.971Z workers [f9l7r] Test executed: addValues works\n',
    '2021-12-11T18:20:58.975Z workers [f9l7r] Run 1 test(s), skipped 0 test(s)\n',
    '2021-12-11T18:20:58.975Z workers Jest Test Run Complete (f9l7r): 2021-12-11T18:20:58.966Z\n',
    '2021-12-11T18:20:58.980Z workers [f9l7r] Sandbox is responsive, closing it\n',
    '2021-12-11T18:20:58.981Z project Test run finished\n',
    '2021-12-11T18:20:58.982Z project Processed console.log entries\n',
    '2021-12-11T18:20:58.982Z project Processed loading sequences\n',
    '2021-12-11T18:20:58.982Z project Processed executed tests\n',
    '2021-12-11T18:20:58.983Z project Processed code coverage\n',
    '2021-12-11T18:20:58.996Z project Test run result processed and sent to IDE\n',
    '2021-12-11T18:21:53.047Z fs File changed in editor: index.ts\n',
    '2021-12-11T18:21:53.048Z extended-core New file or complex file change\n',
    '2021-12-11T18:21:53.057Z project Test run started; run priority: 2\n',
    '2021-12-11T18:21:53.057Z testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 1\n',
    '2021-12-11T18:21:53.058Z workers Starting test run, priority: 2\n',
    '2021-12-11T18:21:53.058Z nodeRunner Starting sandbox [worker #0, session #nren4]\n',
    '2021-12-11T18:21:53.058Z nodeRunner Preparing sandbox [worker #0, session #nren4]\n',
    '2021-12-11T18:21:53.058Z nodeRunner Prepared sandbox [worker #0, session #nren4]\n',
    '2021-12-11T18:21:53.058Z workers [worker #0, session #nren4] Running tests in sandbox\n',
    '2021-12-11T18:21:53.578Z workers Scheduling Jest Test Run (nren4): 2021-12-11T18:21:53.061Z\n',
    '2021-12-11T18:21:53.584Z workers [nren4] Loaded unknown number of test(s)\n',
    '2021-12-11T18:21:53.584Z workers [nren4] Test executed: addValues works\n',
    '2021-12-11T18:21:53.588Z workers [nren4] Run 1 test(s), skipped 0 test(s)\n',
    '2021-12-11T18:21:53.588Z workers Jest Test Run Complete (nren4): 2021-12-11T18:21:53.576Z\n',
    '2021-12-11T18:21:53.589Z workers [nren4] Sandbox is responsive, closing it\n',
    '2021-12-11T18:21:53.590Z project Test run finished\n',
    '2021-12-11T18:21:53.590Z project Processed console.log entries\n',
    '2021-12-11T18:21:53.590Z project Processed loading sequences\n',
    '2021-12-11T18:21:53.590Z project Processed executed tests\n',
    '2021-12-11T18:21:53.591Z project Processed code coverage\n',
    '2021-12-11T18:21:53.597Z project Test run result processed and sent to IDE\n',
    '2021-12-11T18:21:53.851Z fs File changed: index.ts\n',
    '2021-12-11T18:21:53.854Z fs No changes detected for index.ts\n',
    '2021-12-11T18:21:53.855Z extended-core File was not changed, but file markers may need to be synced\n',
    '2021-12-11T18:23:10.216Z project Requested to run some tests\n',
    '2021-12-11T18:23:10.216Z project Debugger start test run\n',
    '2021-12-11T18:23:10.218Z project Test run started; run priority: 1\n',
    '2021-12-11T18:23:10.218Z testTask Test files from affected: 0, from deleted or manually requested: 1, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:23:10.221Z workers Starting test run, priority: 1\n',
    '2021-12-11T18:23:10.221Z nodeRunner Starting sandbox [worker #0, session #6m5tn]\n',
    '2021-12-11T18:23:10.221Z nodeRunner Preparing sandbox [worker #0, session #6m5tn]\n',
    '2021-12-11T18:23:10.221Z nodeRunner Prepared sandbox [worker #0, session #6m5tn]\n',
    '2021-12-11T18:23:10.222Z workers [worker #0, session #6m5tn] Running tests in sandbox\n',
    '2021-12-11T18:23:10.364Z workers Scheduling Jest Test Run (6m5tn): 2021-12-11T18:23:10.227Z\n',
    '2021-12-11T18:23:10.365Z workers [6m5tn] Loaded unknown number of test(s)\n',
    '2021-12-11T18:23:10.366Z workers [6m5tn] Test executed: addValues works\n',
    '2021-12-11T18:23:10.368Z workers [6m5tn] Run 1 test(s), skipped 0 test(s)\n',
    '2021-12-11T18:23:10.369Z workers Jest Test Run Complete (6m5tn): 2021-12-11T18:23:10.363Z\n',
    '2021-12-11T18:23:10.370Z workers [6m5tn] Sandbox is responsive, closing it\n',
    '2021-12-11T18:23:10.370Z project Test run finished\n',
    '2021-12-11T18:23:10.370Z project Processed console.log entries\n',
    '2021-12-11T18:23:10.370Z project Processed loading sequences\n',
    '2021-12-11T18:23:10.370Z project Processed executed tests\n',
    '2021-12-11T18:23:10.370Z project Processed code coverage\n',
    '2021-12-11T18:23:10.371Z project Processed code trace\n',
    '2021-12-11T18:23:10.389Z project Test run result processed and sent to IDE\n',
    '2021-12-11T18:23:19.010Z fs File changed in editor: index.ts\n',
    '2021-12-11T18:23:19.023Z project Test run started; run priority: 2\n',
    '2021-12-11T18:23:19.024Z workers Starting test run, priority: 2\n',
    '2021-12-11T18:23:19.024Z nodeRunner Starting sandbox [worker #0, session #txcma]\n',
    '2021-12-11T18:23:19.025Z nodeRunner Preparing sandbox [worker #0, session #txcma]\n',
    '2021-12-11T18:23:19.025Z nodeRunner Prepared sandbox [worker #0, session #txcma]\n',
    '2021-12-11T18:23:19.025Z workers [worker #0, session #txcma] Running tests in sandbox\n',
    '2021-12-11T18:23:19.229Z workers Scheduling Jest Test Run (txcma): 2021-12-11T18:23:19.027Z\n',
    '2021-12-11T18:23:19.232Z workers [txcma] Loaded unknown number of test(s)\n',
    '2021-12-11T18:23:19.234Z workers [txcma] Test executed: addValues works\n',
    '2021-12-11T18:23:19.237Z workers [txcma] Run 1 test(s), skipped 0 test(s)\n',
    '2021-12-11T18:23:19.237Z workers Jest Test Run Complete (txcma): 2021-12-11T18:23:19.228Z\n',
    '2021-12-11T18:23:19.241Z workers [txcma] Sandbox is responsive, closing it\n',
    '2021-12-11T18:23:19.241Z project Test run finished\n',
    '2021-12-11T18:23:19.242Z project Processed console.log entries\n',
    '2021-12-11T18:23:19.242Z project Processed loading sequences\n',
    '2021-12-11T18:23:19.242Z project Processed executed tests\n',
    '2021-12-11T18:23:19.242Z project Processed code coverage\n',
    '2021-12-11T18:23:19.242Z project Processed code trace\n',
    '2021-12-11T18:23:19.247Z project Test run result processed and sent to IDE\n',
    '2021-12-11T18:23:22.127Z fs File changed in editor: index.ts\n',
    '2021-12-11T18:23:22.139Z project Test run started; run priority: 2\n',
    '2021-12-11T18:23:22.140Z workers Starting test run, priority: 2\n',
    '2021-12-11T18:23:22.140Z nodeRunner Starting sandbox [worker #0, session #ijzhn]\n',
    '2021-12-11T18:23:22.140Z nodeRunner Preparing sandbox [worker #0, session #ijzhn]\n',
    '2021-12-11T18:23:22.140Z nodeRunner Prepared sandbox [worker #0, session #ijzhn]\n',
    '2021-12-11T18:23:22.140Z workers [worker #0, session #ijzhn] Running tests in sandbox\n',
    '2021-12-11T18:23:22.338Z workers Scheduling Jest Test Run (ijzhn): 2021-12-11T18:23:22.143Z\n',
    '2021-12-11T18:23:22.341Z workers [ijzhn] Loaded unknown number of test(s)\n',
    '2021-12-11T18:23:22.342Z workers [ijzhn] Test executed: addValues works\n',
    '2021-12-11T18:23:22.344Z workers [ijzhn] Run 1 test(s), skipped 0 test(s)\n',
    '2021-12-11T18:23:22.345Z workers Jest Test Run Complete (ijzhn): 2021-12-11T18:23:22.336Z\n',
    '2021-12-11T18:23:22.345Z workers [ijzhn] Sandbox is responsive, closing it\n',
    '2021-12-11T18:23:22.346Z project Test run finished\n',
    '2021-12-11T18:23:22.346Z project Processed console.log entries\n',
    '2021-12-11T18:23:22.346Z project Processed loading sequences\n',
    '2021-12-11T18:23:22.346Z project Processed executed tests\n',
    '2021-12-11T18:23:22.346Z project Processed code coverage\n',
    '2021-12-11T18:23:22.346Z project Processed code trace\n',
    '2021-12-11T18:23:22.350Z project Test run result processed and sent to IDE\n',
    '2021-12-11T18:23:33.939Z project Debugger stopped\n',
    '2021-12-11T18:23:33.942Z project Test run started; run priority: 2\n',
    '2021-12-11T18:23:33.943Z testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 1\n',
    '2021-12-11T18:23:33.951Z workers Starting test run, priority: 2\n',
    '2021-12-11T18:23:33.951Z nodeRunner Starting sandbox [worker #0, session #3n9un]\n',
    '2021-12-11T18:23:33.952Z nodeRunner Preparing sandbox [worker #0, session #3n9un]\n',
    '2021-12-11T18:23:33.952Z nodeRunner Prepared sandbox [worker #0, session #3n9un]\n',
    '2021-12-11T18:23:33.952Z workers [worker #0, session #3n9un] Running tests in sandbox\n',
    '2021-12-11T18:23:34.084Z workers Scheduling Jest Test Run (3n9un): 2021-12-11T18:23:33.957Z\n',
    '2021-12-11T18:23:34.084Z workers [3n9un] Loaded unknown number of test(s)\n',
    '2021-12-11T18:23:34.086Z workers [3n9un] Test executed: addValues works\n',
    '2021-12-11T18:23:34.088Z workers [3n9un] Run 1 test(s), skipped 0 test(s)\n',
    '2021-12-11T18:23:34.088Z workers Jest Test Run Complete (3n9un): 2021-12-11T18:23:34.083Z\n',
    '2021-12-11T18:23:34.089Z workers [3n9un] Sandbox is responsive, closing it\n',
    '2021-12-11T18:23:34.089Z project Test run finished\n',
    '2021-12-11T18:23:34.089Z project Processed console.log entries\n',
    '2021-12-11T18:23:34.089Z project Processed loading sequences\n',
    '2021-12-11T18:23:34.089Z project Processed executed tests\n',
    '2021-12-11T18:23:34.090Z project Processed code coverage\n',
    '2021-12-11T18:23:34.092Z project Test run result processed and sent to IDE\n',
    '2021-12-11T18:25:04.144Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:04.144Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:04.145Z project Test run finished\n',
    '2021-12-11T18:25:04.146Z project Test run data re-queued\n',
    '2021-12-11T18:25:08.315Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:08.333Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:08.333Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:08.336Z project Test run finished\n',
    '2021-12-11T18:25:08.336Z project Test run data re-queued\n',
    '2021-12-11T18:25:08.506Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:08.512Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:08.512Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:08.513Z project Test run finished\n',
    '2021-12-11T18:25:08.513Z project Test run data re-queued\n',
    '2021-12-11T18:25:09.191Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:09.196Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:09.196Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:09.197Z project Test run finished\n',
    '2021-12-11T18:25:09.197Z project Test run data re-queued\n',
    '2021-12-11T18:25:09.736Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:09.741Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:09.741Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:09.742Z project Test run finished\n',
    '2021-12-11T18:25:09.742Z project Test run data re-queued\n',
    '2021-12-11T18:25:09.981Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:09.986Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:09.986Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:09.987Z project Test run finished\n',
    '2021-12-11T18:25:09.987Z project Test run data re-queued\n',
    '2021-12-11T18:25:10.178Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:10.183Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:10.183Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:10.183Z project Test run finished\n',
    '2021-12-11T18:25:10.183Z project Test run data re-queued\n',
    '2021-12-11T18:25:11.747Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:11.752Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:11.752Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:11.753Z project Test run finished\n',
    '2021-12-11T18:25:11.753Z project Test run data re-queued\n',
    '2021-12-11T18:25:12.019Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:12.024Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:12.024Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:12.024Z project Test run finished\n',
    '2021-12-11T18:25:12.024Z project Test run data re-queued\n',
    '2021-12-11T18:25:12.188Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:12.195Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:12.195Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:12.196Z project Test run finished\n',
    '2021-12-11T18:25:12.196Z project Test run data re-queued\n',
    '2021-12-11T18:25:12.298Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:12.303Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:12.303Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:12.304Z project Test run finished\n',
    '2021-12-11T18:25:12.304Z project Test run data re-queued\n',
    '2021-12-11T18:25:12.461Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:12.466Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:12.466Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:12.466Z project Test run finished\n',
    '2021-12-11T18:25:12.466Z project Test run data re-queued\n',
    '2021-12-11T18:25:12.818Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:12.824Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:12.824Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:12.825Z project Test run finished\n',
    '2021-12-11T18:25:12.825Z project Test run data re-queued\n',
    '2021-12-11T18:25:16.026Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:16.031Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:16.031Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:16.031Z project Test run finished\n',
    '2021-12-11T18:25:16.031Z project Test run data re-queued\n',
    '2021-12-11T18:25:17.152Z fs File changed: .gitignore\n',
    '2021-12-11T18:25:17.158Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:17.158Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:17.158Z project Test run finished\n',
    '2021-12-11T18:25:17.158Z project Test run data re-queued\n',
    '2021-12-11T18:25:17.234Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:17.234Z fs No changes detected for .gitignore\n',
    '2021-12-11T18:25:24.331Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:24.337Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:24.337Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:24.337Z project Test run finished\n',
    '2021-12-11T18:25:24.338Z project Test run data re-queued\n',
    '2021-12-11T18:25:24.678Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:24.682Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:24.684Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:24.684Z project Test run finished\n',
    '2021-12-11T18:25:24.684Z project Test run data re-queued\n',
    '2021-12-11T18:25:24.837Z fs File changed in editor: .gitignore\n',
    '2021-12-11T18:25:24.843Z project Test run started; run priority: 2\n',
    '2021-12-11T18:25:24.843Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2021-12-11T18:25:24.843Z project Test run finished\n',
    '2021-12-11T18:25:24.843Z project Test run data re-queued\n',
    '2021-12-11T18:25:25.158Z fs File changed: .gitignore\n',
    '2021-12-11T18:25:25.160Z fs No changes detected for .gitignore\n',
    '2021-12-11T18:25:25.160Z extended-core File was not changed, but file markers may need to be synced\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo. The issue is now fixed and the fix is published in [the latest Wallaby Core v1.0.1189](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by vjau** [comment]
Thank you for the quick fix. However there is still a problem with objects. I have updated the repo.
Also if you try to look at the value of ```this.objs``` on line 20 of index.ts, you will receive an error ```cannot convert a symbol value to a string```

**Comment by ArtemGovorov** [comment]
Thanks for checking. The issues are now fixed and the fix is published in [the latest Wallaby Core v1.0.1190](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). Please note that mobx proxy symbol will still be visible (by design) in Value Explorer (it reveals hidden properties unlike plain console.log). It is because the object is still a "proxy" (in both Wallaby and Jest CLI), but the symbol data on the object should not interfere with assertion diffs or inline logs.

**Comment by vjau** [comment]
Thank you. 
Could you please think about a future feature where you could define custom formatters for the debugger like what chrome is doing ?
For this specific use case, the formatter should be able to call mobx ```toJS``` function on the value to display.

**Comment by ArtemGovorov** [comment]
> Could you please think about a future feature where you could define custom formatters for the debugger like what chrome is doing ?

Sounds interesting, I have created the feature request at https://github.com/wallabyjs/public/issues/2875.

For now you may use a simple live comment (may even create a [WS live template](https://www.jetbrains.com/webstorm/guide/tips/save-as-live-template/) to quickly insert it) to get the compact view:

```js
  const instance = new FooClass();
  instance.addObj({name:"bar"});

  instance //? require('mobx').toJS($)
```
