### ISSUE TITLE
Vitest and Yarn PnP raises an `Automatic Jest configuration error` on startup

### ISSUE THREAD

**Issue by spdiswal** [wallabyjs/public#3142]
### Issue description or question

Hi Wallaby team!

I am having some trouble starting Wallaby for Vitest and Yarn in PnP mode.

It says:
```
Automatic Jest configuration error: Module jest-cli is not found in '.'.

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Vitest configuration error: (node:21032) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Directory import '.' is not supported resolving ES modules imported from [wallaby core]\server.js
```

This happens in IntelliJ IDEA and in VS Code. I am using the automatic configuration for Wallaby.

When I use npm instead of Yarn, it works like a charm.

Repository: https://github.com/spdiswal/wallaby-vitest-yarn

### Wallaby diagnostics report

**Yarn** (the `main` branch)
Not available; the menu item in IntelliJ IDEA is greyed out, and it does not appear in the VS Code command palette.

**npm** (the `npm-workaround` branch)
```
{
  editorVersion: 'IntelliJ IDEA 2022.3.1',
  pluginVersion: '1.0.257',
  editorType: 'IntelliJ',
  osVersion: 'win32 10.0.19045',
  nodeVersion: 'v18.12.1',
  coreVersion: '1.0.1364',
  checksum: 'YmM0ZjAxNmNlMWEzZjQyNDg1YTkyNjExY2NiNzg2ZGMsMTcwMTY0ODAwMDAwMCww',
  config: {
    diagnostics: {
      vitest: {
        file: { config: 'import { defineConfig } from "vitest/config"\n\nexport default defineConfig({\n\ttest: {\n\t\tinclude: ["**/*.spec.ts"],\n\t},\n})\n' },
        config: {
          allowOnly: true,
          watch: true,
          globals: false,
          environment: 'node',
          threads: true,
          clearMocks: false,
          restoreMocks: false,
          mockReset: false,
          include: [ '**/*.spec.ts' ],
          exclude: [ '**/node_modules/**', '**/dist/**', '**/cypress/**', '**/.{idea,git,cache,output,temp}/**', '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress}.config.*' ],
          testTimeout: 5000,
          hookTimeout: 10000,
          teardownTimeout: 1000,
          isolate: true,
          watchExclude: [ '**/node_modules/**', '**/dist/**' ],
          forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
          update: false,
          reporters: [ 'default' ],
          silent: false,
          ui: false,
          uiBase: '/__vitest__/',
          open: true,
          css: { include: [], modules: { classNameStrategy: 'stable' } },
          coverage: {
            all: false,
            provider: 'c8',
            enabled: false,
            clean: true,
            cleanOnRerun: true,
            reportsDirectory: './coverage',
            excludeNodeModules: true,
            exclude: [
              'coverage/**',
              'dist/**',
              'packages/*/test{,s}/**',
              '**/*.d.ts',
              'cypress/**',
              'test{,s}/**',
              'test{,-*}.{js,cjs,mjs,ts,tsx,jsx}',
              '**/*{.,-}test.{js,cjs,mjs,ts,tsx,jsx}',
              '**/*{.,-}spec.{js,cjs,mjs,ts,tsx,jsx}',
              '**/__tests__/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress}.config.*',
              '**/.{eslint,mocha,prettier}rc.{js,cjs,yml}'
            ],
            reporter: [ 'text', 'html', 'clover', 'json' ],
            allowExternal: false,
            extension: [
              '.js',  '.cjs',
              '.mjs', '.ts',
              '.mts', '.cts',
              '.tsx', '.jsx',
              '.vue', '.svelte'
            ]
          },
          fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
          maxConcurrency: 5,
          dangerouslyIgnoreUnhandledErrors: false,
          typecheck: {
            checker: 'tsc',
            include: [ '**/*.{test,spec}-d.{ts,js}' ],
            exclude: [ '**/node_modules/**', '**/dist/**', '**/cypress/**', '**/.{idea,git,cache,output,temp}/**', '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress}.config.*' ]
          },
          slowTestThreshold: 300,
          defines: {},
          root: 'D:/playground/wallaby-vitest-yarn',
          mode: [],
          deps: { inline: [ {}, {}, {}, {}, {}, {}, '@nuxt/test-utils' ], registerNodeLoader: false },
          snapshotOptions: { snapshotFormat: {}, updateSnapshot: 'new' },
          setupFiles: [],
          cache: { dir: 'D:/playground/wallaby-vitest-yarn/node_modules/.vitest' },
          sequence: { hooks: 'parallel' },
          package: {
            version: '0.27.0',
            urls: { hooks: 'file:///C:/Users/sdi/AppData/Local/JetBrains/IntelliJIdea2022.3/wallaby/wallaby/runners/node/hooks.mjs' },
            paths: { root: 'D:\\playground\\wallaby-vitest-yarn\\node_modules\\vitest', dist: 'D:\\playground\\wallaby-vitest-yarn\\node_modules\\vitest\\dist' }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: '**/*.spec.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress}.config.*', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/*.spec.ts', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: { runner: '--experimental-loader=file:///C:/Users/sdi/AppData/Local/JetBrains/IntelliJIdea2022.3/wallaby/wallaby/runners/node/hooks.mjs' },
      runner: 'C:\\Program Files\\nodejs\\node.exe',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: undefined,
    configCode: 'auto.detect#619596721'
  },
  packageJSON: { dependencies: undefined, devDependencies: { typescript: '4.9.4', vite: '4.0.4', vitest: '0.27.0' } },
  fs: { numberOfFiles: 4 },
  debug: []
}
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. We've identified the cause and we're working on a fix. We'll provide an update when the fix is available.

**Comment by smcenlly** [comment]
We've fixed the problem in the latest version of Wallaby. Wallaby should automatically restart with the latest version and fix your problem. If it does not, please [follow these steps](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to force Wallaby core to update.

**Comment by spdiswal** [comment]
Thanks a lot for looking into this and providing an update!
I am still having some issues, however.

Upon starting up, it is noticeably slower to provide a response. And then it says:

```
wallaby.js started
core v1.0.1366
Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'.

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Vitest configuration error: (node:15044) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

<--- Last few GCs --->

[15044:00000164A44A8CF0]    26776 ms: Scavenge 4048.6 (4131.8) -> 4047.9 (4142.0) MB, 14.6 / 0.0 ms  (average mu = 0.792, current mu = 0.566) allocation failure; 
[15044:00000164A44A8CF0]    28551 ms: Mark-sweep 4052.1 (4143.1) -> 4049.6 (4144.9) MB, 1766.1 / 0.0 ms  (average mu = 0.568, current mu = 0.053) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6CCFE1B7F node_api_throw_syntax_error+203775
 2: 00007FF6CCF61556 v8::internal::wasm::WasmCode::safepoint_table_offset+63558
 3: 00007FF6CCF628C2 v8::internal::wasm::WasmCode::safepoint_table_offset+68530
 4: 00007FF6CDA047F4 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF6CD9EFB52 v8::Isolate::Exit+674
 6: 00007FF6CD871BBC v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
 7: 00007FF6CD86EDDB v8::internal::Heap::CollectGarbage+3963
 8: 00007FF6CD885013 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
 9: 00007FF6CD8858BD v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
10: 00007FF6CD88E20A v8::internal::Factory::AllocateRaw+810
11: 00007FF6CD8A4B2A v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller+90
12: 00007FF6CD8A4A3D v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArray+77
13: 00007FF6CD68A430 v8::internal::FixedArray::SetAndGrow+128
14: 00007FF6CD8D2017 v8::internal::Isolate::Allocate+1015
15: 00007FF6CD8D1F76 v8::internal::Isolate::Allocate+854
16: 00007FF6CD8D2CCC v8::internal::Isolate::CaptureAndSetErrorStack+2348
17: 00007FF6CD8D2A6D v8::internal::Isolate::CaptureAndSetErrorStack+1741
18: 00007FF6CD8D3606 v8::internal::Isolate::CaptureDetailedStackTrace+950
19: 00007FF6CD8D2645 v8::internal::Isolate::CaptureAndSetErrorStack+677
20: 00007FF6CD9A427E v8::internal::Builtins::code+145326
21: 00007FF6CD9A3FF0 v8::internal::Builtins::code+144672
22: 00007FF6CDAA1F81 v8::internal::SetupIsolateDelegate::SetupHeap+558449
23: 00007FF64DC26A4E 

Please refer to our docs: https://wallabyjs.com/docs/config/overview.html 
```

This occurs with Yarn in the same repository and environment as described in the original post. The diagnostics report remains unavailable in this case. With npm, Wallaby works correctly and starts up in its normal pace.

**Comment by smcenlly** [comment]
We couldn't reproduce your out of memory issue but we did find another problem that may be causing your issue.

Could you please update to Wallaby core `v1.0.1367` and let us know if it's working for you? If Wallaby does not automatically update for you, please [follow these steps](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to force Wallaby core to update.

**Comment by smcenlly** [comment]
Closing this issue since we haven't heard back. If you're still having problems, please let us know.
