### ISSUE TITLE
Creating or deleting a large number of files will cause the test to fail.

### ISSUE THREAD

**Issue by CaryTrivett** [wallabyjs/public#3256]
### Issue description or question

I will create a node_modules in the beforeAll of the test, then start a nodejs server, and then shut down the server in afterAll and delete the node_modules.

### Error

<img width="984" alt="image" src="https://github.com/wallabyjs/public/assets/90044465/6efdcda3-8181-41a3-9687-fbb78afc75ce">

**Comment by CaryTrivett** [comment]
[report.md](https://github.com/wallabyjs/public/files/12293492/report.md)

Wallaby diagnostics report

**Comment by CaryTrivett** [comment]
The following code can be reproduced.


```
import fs from "fs/promises";
import { resolve } from "path";
import { afterAll, beforeAll, describe, it } from "vitest";

const __dirname = import.meta.url.slice(7, import.meta.url.lastIndexOf("/"));

describe("", () => {
  const randomName = Math.random();
  const rootDir = resolve(__dirname, "tmp", `${randomName}`);

  beforeAll(async () => {
    await fs.mkdir(rootDir, {
      recursive: true,
    });
    for (let i = 0; i < 10000; i++) {
      await fs.writeFile(
        resolve(__dirname, "tmp", `${randomName}`, `file-${i}`),
        "1"
      );
    }
  });

  afterAll(async () => {
    await fs.rm(rootDir, { recursive: true });
  });

  it("", async () => {
    console.log(1);
  });
});

```

**Comment by mburnell** [comment]
Thanks for reporting the issue. While we were not able to reproduce the exact error you reported, we were able to get Wallaby into a similar bad state caused by Wallaby reacting to the files written to `tmp`. This issue was resolved for us by adding the tmp directory to our `vitest.config.ts`:
```javascript

/// <reference types="vitest" />
import { defineConfig } from 'vite'

export default defineConfig({
  test: {
    exclude: [/* other excludes go here...*/ '**/tmp/**']
  },
})
```

Please try using similar config to ensure Wallaby doesn't attempt to monitor such files. If this doesn't resolve your issue, please provide your vitest config and Wallaby diagnostics report (obtainable using the `Copy Diagnostics Report` command).

**Comment by CaryTrivett** [comment]
> Thanks for reporting the issue. While we were not able to reproduce the exact error you reported, we were able to get Wallaby into a similar bad state caused by Wallaby reacting to the files written to `tmp`. This issue was resolved for us by adding the tmp directory to our `vitest.config.ts`:
> 
> ```js
> /// <reference types="vitest" />
> import { defineConfig } from 'vite'
> 
> export default defineConfig({
>   test: {
>     exclude: [/* other excludes go here...*/ '**/tmp/**']
>   },
> })
> ```
> 
> Please try using similar config to ensure Wallaby doesn't attempt to monitor such files. If this doesn't resolve your issue, please provide your vitest config and Wallaby diagnostics report (obtainable using the `Copy Diagnostics Report` command).

github.com:CaryTrivett/wallaby-demo.git

I still have a similar issue on my end.

I have created a reproducible project, and I put Wallaby Diagnostics Report in the `Wallaby Diagnostics Report.mdI wrote down the reproduction method in readme.md

**Comment by smcenlly** [comment]
Thank you for the sample repo, and for your diagnostics report. We were able to determine the cause.

It seems on MacOS (at least - we're not sure if other operating systems are affected), when using a File System watcher to detect file add/remove/changes, when you run `await fs.rm(rootDir, { recursive: true });` on a large number of files, **ALL** files are reported as being deleted, not just the files that are actually deleted.

Interestingly, this also affects `vitest`, but does not result in a runtime error like it does for Wallaby.

You can see the same issue being exhibited in `vitest` by running `npx vitest --outputFile log.txt`. You will see that `vitest` incorrectly reports that the test was removed with a negative test duration:

<img width="902" alt="image" src="https://github.com/wallabyjs/public/assets/2074089/84982752-674c-4e14-96b5-4ff1bdd70111">

---

We've implemented a workaround in Wallaby core `v1.0.1458` to fix this problem. Please run the `Wallaby.js: Force Core Update` command in VS Code to update to the latest version immediately.

**Comment by CaryTrivett** [comment]
> Thank you for the sample repo, and for your diagnostics report. We were able to determine the cause.
> 
> It seems on MacOS (at least - we're not sure if other operating systems are affected), when using a File System watcher to detect file add/remove/changes, when you run `await fs.rm(rootDir, { recursive: true });` on a large number of files, **ALL** files are reported as being deleted, not just the files that are actually deleted.
> 
> Interestingly, this also affects `vitest`, but does not result in a runtime error like it does for Wallaby.
> 
> You can see the same issue being exhibited in `vitest` by running `npx vitest --outputFile log.txt`. You will see that `vitest` incorrectly reports that the test was removed with a negative test duration:
> 
> <img alt="image" width="902" src="https://user-images.githubusercontent.com/2074089/259288179-84982752-674c-4e14-96b5-4ff1bdd70111.png">
> We've implemented a workaround in Wallaby core `v1.0.1458` to fix this problem. Please run the `Wallaby.js: Force Core Update` command in VS Code to update to the latest version immediately.

https://github.com/paulmillr/chokidar/issues/1117

this is a bug of chokidar.  vite use chokidar  for watch.
