### ISSUE TITLE
resolveTo requires global Promise, or Promise configured with `jasmine.getEnv().configure()

### ISSUE THREAD

**Issue by jamiekemp** [wallabyjs/public#3293]
Getting this issue:

resolveTo requires global Promise, or Promise configured with `jasmine.getEnv().configure()

for jasmine spies such as:

spyOn(app, 'test').and.resolveTo('data');

Verified by spinning up a new Angular 14 app, and using auto config. Is resolveTo not support because it's Jasmine Edge? This practice is used extensively in our current app, so prefer not refactor it.

**Comment by Malstrime** [comment]
I faced today the same problem.

Also there are failing tests with: 
`Error: An asynchronous before/it/after function took a done callback but also returned a promise. Either remove the done callback (recommended) or change the function to not return a promise.`

All failed tests are **async** or **fakeAsync**.

Angular 15.2.3 / Jasmine 3.8.0 / Wallaby v1.0.1490

**Comment by jamiekemp** [comment]
I don't think that's the same problem :) Happy to advise if you paste in the full test.

**Comment by smcenlly** [comment]
Yesterday we added support for `jasmine@4.x` and `jasmine@5.x`, and updated `jasmine@5.x` to be the default as everything seemed to be backward compatible. 

I suspect both of your issues are related to that.

We have rolled back the default version to `jasmine@3.x`, which I think should fix both problems.

Please update to Wallaby core `v1.0.1491`. If you're still having problems, please let us know.

**Comment by Malstrime** [comment]
It works now, thanks! (updated to v1.0.1492)

**Comment by jamiekemp** [comment]
Thanks :) 

It works now in v1.0.1491, but the issue still exists versions v1.0.1492  to v1.0.1495.

**Comment by jamiekemp** [comment]
How do I stop IntelliJ automatically updating it to v1.0.1495 ? It keeps replacing with the latest version.

**Comment by smcenlly** [comment]
We identified that cause of your problem. The project template (Angular v14) is using Jasmine 4, and there was a bug in Wallaby's new Jasmine 4 integration.

This has been fixed in Wallaby core `v1.0.1496`.

We have also updated our Wallaby for IntelliJ plugin to include a new `Auto Update` setting (on by default) in plugin version `1.0.282`.

![image](https://github.com/wallabyjs/public/assets/2074089/e19e9863-c99e-4437-a127-b87885f240ab)

Please note it may take a day for the plugin update to become available in the marketplace. If you need the latest version immediately, you can [download](https://wallaby-downloads.s3.amazonaws.com/wallaby-intellij-v1.0.282.zip) the zip file and install it manually using `Install Plugin from Disk`:

<img width="491" alt="image" src="https://github.com/wallabyjs/public/assets/2074089/c5027dc1-20ec-45dc-8bf1-23c33867a43f">

**Comment by smcenlly** [comment]
Closing this issue, as it should be working in the latest version. If you're still having problems, please let us know and we will reopen the issue.

**Comment by georgboeser** [comment]
we use Wallaby in a nestJS backend, and for me, it is still a problem. i already updated to v1.0.1497. do you have any advise?

**Comment by smcenlly** [comment]
@georgboeser - thanks for reporting your problem. Jasmine@5.1.x was working for browser-based tests, but not for node.js tests.

It should work for you now using the latest version of Wallaby core, `v1.0.1498`.

**Comment by georgboeser** [comment]
yes

v1.0.1498 fixed the problem. thank you Wallaby. you are awesome 👍

**Comment by jamiekemp** [comment]
Thanks, this fixes it :)
