### ISSUE TITLE
Wallaby running with pnp can't find Vitest

### ISSUE THREAD

**Issue by asaf-wlodawer-sage** [wallabyjs/public#3311]
### Issue description or question

Hi,
I have a project running with nx, yarn with `nodeLinker: pnp` and it seems to cause an error trying to detect Vitest.
I created a project with the same error for review.

https://github.com/asaf-wlodawer-sage/wallaby-config

### Wallaby diagnostics report

‍​[Info]​ Started Wallaby.js Core v1.0.1514
​​[Error] Failed to load configuration file: Automatic Angular CLI configuration error: Cannot detect @nx/workspace package version, is the package installed?​​
​​[Error] We've also tried to automatically configure Wallaby.js for other frameworks​​
​​[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'.​​
​​[Error] Automatic Vitest configuration error: Cannot find module '/Users/asafwlodawer/Projects/wallaby-config/.yarn/__virtual__/vitest-virtual-e0aed190d1/0/cache/vitest-npm-1.1.0-14b6057a75-5e4ac0231b.zip/node_modules/vitest/dist/vendor/node.i3Lxw5di.js' imported from [wallaby core]/server.js​​
​​[Error]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)​​
​​[Error] Please refer to our docs: https://wallabyjs.com/docs/config/overview.html ​​

**Comment by smcenlly** [comment]
Thanks for the sample repo. 

Unfortunately we can't get the tests running for your project outside of Wallaby. Can you please provide us with instructions to run your tests?

We tried running from the project root with `yarn test` and it hangs:

<img width="450" alt="image" src="https://github.com/wallabyjs/public/assets/2074089/2e6b75c5-ebac-4c93-92ab-16bac11f31e1">

We also tried running from the `frontend/app` directory with `yarn test` and we get an error:

<img width="907" alt="image" src="https://github.com/wallabyjs/public/assets/2074089/5184488d-6252-435c-a086-93188e5a32a6">

We'd like to understand how the tests are running outside of Wallaby before trying to understand why Wallaby isn't working.

**Comment by asaf-wlodawer-sage** [comment]
Hi,
I fixed the project, now it works with `yarn test`

<img width="941" alt="image" src="https://github.com/wallabyjs/public/assets/93931283/c3dda6b0-1d49-4795-8afd-0a012a8bdd48">

**Comment by smcenlly** [comment]
Thanks for updating the repo. Wallaby actually requires that your tests will run from your repo root, and they still fail in your case. You can get the tests running from the repo root by adding a `vitest.workspace.ts` configuration file (also requires updates to your `package.json` dependencies); no need to make these changes; they were simple and we've been able to get things running.

**`/vitest.workspace.ts`**
```typescript
export default [
  'frontend/*'
];
```

After running Wallaby from the root of the repo, we have identified recent breaking changes with later versions of `node` and `yarn` that are preventing Wallaby from working with vitest. 

We are working on a fix and hope to have this available for you tomorrow.

**Comment by smcenlly** [comment]
Please [update to Wallaby core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) `v1.0.1516`.

Please make sure that you have the `vitest.workspace.ts` in your project root as per our last reply.

Because you have `jest` and `@nx/jest` as dependencies of your root project `/package.json`. You will need to add `vitest` dependencies and configure Wallaby to only run for `vitest`:

**`/package.json`** changes (run `yarn install --dev` after adding these)
```diff
{
  "devDependencies": {
    ...
    "@vitest/runner": "^1.1.0",
    "@vitest/snapshot": "^1.1.0",
    "vitest": "^1.1.0"
  }
}
```

**`/wallaby.js`** configuration file (**you must select this file as your Wallaby Configuration**)
```javascript
module.exports = ({
  // Tell Wallaby not to use jest
  autoDetect: ['vitest'],
});
```
