### ISSUE TITLE
Run single test with coverage

### ISSUE THREAD

**Issue by lcorneliussen** [wallabyjs/public#465]
It would be extremely helpful to be able to run a single test and thus reduce inline-information of coverage and console.logs to that test only.

**Comment by ArtemGovorov** [comment]
Testing frameworks provide a way to do it, for example if you are using jasmine you may change a test function from `it` to `fit`:
```javascript
  fit('only this test will run', () => {
  });
```
or if you are suing mocha, you may use `it.only`:
```javascript
  it.only('only this test will run', () => {
  });
```

Is it what you're looking for, or you had something different in mind?

**Comment by fvanwijk** [comment]
I have the same. When running a test with `ddescribe` or `iit` (jasmine 1.x), Wallaby still shows console.logs from other tests or multiple times output from console.log in the src triggered by multiple tests.
It also runs other tests when making changes.

**Comment by ArtemGovorov** [comment]
@fvanwijk Thanks for the report. It was a bug in jasmine 1.3.x integration, jasmine >=2 and mocha should work as I have described. I have fixed the 1.3.x integration bug in core v1.0.186.

**Comment by lcorneliussen** [comment]
Looks like it still running all test from other files. So code coverage++ still gets polluted

**Comment by ArtemGovorov** [comment]
@lcorneliussen The reason it is running tests from other files is most likely because by default wallaby runs test files in parallel, so a worker running few other specs has no idea that something is requested to run exclusively in another worker. You can verify that by setting [workers count to 1](http://wallabyjs.com/docs/config/workers.html):
```
workers: { initial: 1, regular: 1 }
```

**Comment by chrisblossom** [comment]
@ArtemGovorov I just tested this and confirmed what you said is what is happening. Although it does not update as fluid as you would expect,  if you start wallaby and add/remove to .only, not all tests will start/stop. I suspect this is because of a caching technique that is used for performance.

I would love to see .only to be fully supported in the future. It really helps issues directly related to the test you are trying to work with.

**Comment by tomekwi** [comment]
@ArtemGovorov I can confirm this happens with mocha as well. Only just getting started, but this makes wallaby pretty hard to integrate in my workflows.

**Comment by ArtemGovorov** [comment]
RFC: https://github.com/wallabyjs/public/issues/1156#issuecomment-321125522

**Comment by ArtemGovorov** [comment]
https://github.com/wallabyjs/public/issues/1156#issuecomment-378477149

**Comment by NikGovorov** [comment]
Hi All,

We improved the scenario of focusing a single test by adding new [Test Filtering](https://bit.ly/2CyP32d) feature. 

We would love to hear your feedback!
