### ISSUE TITLE
Binary fixtures copied incorrectly

### ISSUE THREAD

**Issue by jessezhang91** [wallabyjs/public#521]
### Issue description or question

Binary fixtures seem to be copied incorrectly to the wallaby fixtures folder. 

I was originally getting an issue with a *.xlsx file. I tested a *.jpg and that didn't have an issue. I rename the *.jpg to *.bin and the issue arises again.

The actual files:
```
$ ls -sk test.xlsx
16 test.xlsx
$ ls -sk test.bin
 628 test.bin
```

First three lines of hexdump for test.bin:
```
00000000  ff d8 ff e0 00 10 4a 46  49 46 00 01 02 01 00 fa  |......JFIF......|
00000010  00 fa 00 00 ff e1 14 d2  45 78 69 66 00 00 4d 4d  |........Exif..MM|
00000020  00 2a 00 00 00 08 00 07  01 12 00 03 00 00 00 01  |.*..............|
```

The files copied to wallaby instrumented folder (and original) `~/.atom/packages/atom-wallaby/projects/a65a514fedfb8cc8/instrumented/test/fixtures`:
```
$ ls -sk test.xlsx
24 test.xlsx
$ ls -sk test.bin
1156 test.bin
```

First three lines of hexdump for test.bin:
```
00000000  ef bf bd ef bf bd ef bf  bd ef bf bd 00 10 4a 46  |..............JF|
00000010  49 46 00 01 02 01 00 ef  bf bd 00 ef bf bd 00 00  |IF..............|
00000020  ef bf bd ef bf bd 14 ef  bf bd 45 78 69 66 00 00  |..........Exif..|
```

The content in the hexdump looks similar but with some additional bytes. I'm guessing it's being escaped or something.

I've currently worked around this by having my fixture loader script load from the project folder as opposed to the copied fixtures folder.

### Wallaby.js configuration file

```javascript
"use strict";

module.exports = () => {
	return {
		files: [{
			pattern: "test/fixtures/index.js",
			instrument: false,
			load: false
		}, {
			pattern: "test/fixtures/**/*",
			instrument: false,
			load: false
		}, {
			pattern: "src/**/*.js"
		}],
		tests: [
			"test/specs/**/*-spec.js"
		],
		env: {
			type: "node"
		},
		testFramework: "mocha",
		bootstrap: () => {
			"use strict";

			const chai = require("chai"),
				chaiAsPromised = require("chai-as-promised");

			chai.use(chaiAsPromised);

			global.expect = chai.expect;
			global.should = chai.should();

			const path = require("path");
			global.fixturesDir = path.join(global.wallaby.localProjectDir, "test", "fixtures");
		}
	};
};
```

### Code editor or IDE name and version

Atom v1.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
@jessezhang91 Good find, the issue is fixed in wallaby core v1.0.201. The core will be updated automatically in a few minutes after your next wallaby.js restart, to get the update ASAP, you may [force the core update](https://github.com/wallabyjs/public/issues/413#issuecomment-173174486).

**Comment by jessezhang91** [comment]
Hey @ArtemGovorov, this seems to have fixed xlsx and jpg. However, I'm still getting an issue with mp4 and zip.

Original:
```
  4 test.jpg
264 test.zip
244 test.mp4
 44 test.xlsx
```

Copied:
```
  4 test.jpg
496 test.zip
444 test.mp4
 44 test.xlsx
```

**Comment by ArtemGovorov** [comment]
@jessezhang91 Fixed it for zip and mp4 in wallaby core v1.0.202.

**Comment by jeromu** [comment]
Same problem with other extensions:  .irx  and .apk.
