### ISSUE TITLE
wallaby fails to run after updating to core v1.0.296

### ISSUE THREAD

**Issue by ochemerys** [wallabyjs/public#803]
### Issue description or question
How can I return back to stable version?

Just after I updated wallaby, it stopped to work failing with errors

Wallaby Console:
-------------------------
wallaby.js started
core v1.0.296
Error: spawn UNKNOWN
  at exports._errnoException (util.js:874:11)
  at ChildProcess.spawn (internal/child_process.js:298:11)
  at exports.spawn (child_process.js:339:9)
  at f.spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
  at spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
  at startPhantomProcess (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
  at Server.<anonymous> (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:166:7)
  at emitListeningNT (net.js:1260:10)
  at doNTCallback1 (node.js:430:9)
  at process._tickCallback (node.js:352:17)

Error: spawn UNKNOWN
  at exports._errnoException (util.js:874:11)
  at ChildProcess.spawn (internal/child_process.js:298:11)
  at exports.spawn (child_process.js:339:9)
  at f.spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
  at spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
  at startPhantomProcess (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
  at Server.<anonymous> (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:166:7)
  at emitListeningNT (net.js:1260:10)
  at doNTCallback1 (node.js:430:9)
  at process._tickCallback (node.js:352:17)

Error: spawn UNKNOWN
  at exports._errnoException (util.js:874:11)
  at ChildProcess.spawn (internal/child_process.js:298:11)
  at exports.spawn (child_process.js:339:9)
  at f.spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
  at spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
  at startPhantomProcess (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
  at Server.<anonymous> (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:166:7)
  at emitListeningNT (net.js:1260:10)
  at doNTCallback1 (node.js:430:9)
  at process._tickCallback (node.js:352:17)

Error: spawn UNKNOWN
  at exports._errnoException (util.js:874:11)
  at ChildProcess.spawn (internal/child_process.js:298:11)
  at exports.spawn (child_process.js:339:9)
  at f.spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
  at spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
  at startPhantomProcess (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
  at Server.<anonymous> (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:166:7)
  at emitListeningNT (net.js:1260:10)
  at doNTCallback1 (node.js:430:9)
  at process._tickCallback (node.js:352:17)

Error: spawn UNKNOWN
  at exports._errnoException (util.js:874:11)
  at ChildProcess.spawn (internal/child_process.js:298:11)
  at exports.spawn (child_process.js:339:9)
  at f.spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
  at spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
  at startPhantomProcess (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
  at Server.<anonymous> (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:166:7)
  at emitListeningNT (net.js:1260:10)
  at doNTCallback1 (node.js:430:9)
  at process._tickCallback (node.js:352:17)

Error: spawn UNKNOWN
  at exports._errnoException (util.js:874:11)
  at ChildProcess.spawn (internal/child_process.js:298:11)
  at exports.spawn (child_process.js:339:9)
  at f.spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
  at spawn (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
  at startPhantomProcess (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
  at Server.<anonymous> (C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:166:7)
  at emitListeningNT (net.js:1260:10)
  at doNTCallback1 (node.js:430:9)
  at process._tickCallback (node.js:352:17)

### Wallaby.js configuration file

```javascript

module.exports = function () { // wallaby as a parameter to support EC6+
    return {
        "files": [
           {pattern: 'bower_components/angular/angular.js', instrument: false},
            {pattern: 'bower_components/angular-ui-router/release/angular-ui-router.js', instrument: false},
            {pattern: 'bower_components/angular-resource/angular-resource.js', instrument: false},
            {pattern: 'bower_components/angular-bootstrap/ui-bootstrap-tpls.js', instrument: false},
            {pattern: 'bower_components/jquery/dist/jquery.js', instrument: false},
            {pattern: 'bower_components/toastr/toastr.js', instrument: false},
            {pattern: 'bower_components/angular-mocks/angular-mocks.js', instrument: false},
            {pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false},
            {pattern: 'node_modules/jasmine-sinon/lib/jasmine-sinon.js', instrument: false},
            'src/client/app/app.module.js',
            'src/client/app/**/*.js',
            'src/client/app/widgets/*.html',
            '!src/client/app/**/*.spec.js'
        ],
        "tests": [
            'src/client/app/**/*.spec.js',
            'tests/*.spec.js'
        ],
        preprocessors: {
            'src/client/app/widgets/**/*.html': function(file) {
                return require('wallaby-ng-html2js-preprocessor').transform(file, {
                    // strip this from the file path
                    stripPrefix: 'src/client/'
          
                })
            }
        }
    };
};

```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

Windows 7

**Comment by ArtemGovorov** [comment]
Try re-installing the plugin. If it doesn't help, then the reason may be in the [recent switch to PhantomJs 2](https://twitter.com/wallabyjs/status/778840025127538688) by default, [try switching back to PhantomJs 1.9.8](https://wallabyjs.com/docs/integration/phantomjs2.html#phantomjs-198).

**Comment by ochemerys** [comment]
Hmm ... interesting. I have phantomjs@2.1.7  in my project 
when I added 
        env: {
            runner: 'node_modules/phantomjs/bin/phantomjs'
        }
to my wallaby.config.js
the wallaby Version: 1.0.75 is working again, but with phantomjs 2.1.7

**Comment by ArtemGovorov** [comment]
Thanks for the update! I have fixed the issue, when you update the plugin to 1.0.76, it should just work for you without the `runner` setting.

**Comment by ochemerys** [comment]
Thank you for quick response,

Unfortunately 1.0.76 still fails without the runner settings. I tried 
example project wallaby-angular-todomvc-sample from your website and it 
fails on my box too.

My project errors are: (not sure if they are the same as they were for 
1.0.75)

wallaby.js started
core v1.0.296
Error: spawn UNKNOWN
   at exports._errnoException (util.js:874:11)
   at ChildProcess.spawn (internal/child_process.js:298:11)
   at exports.spawn (child_process.js:339:9)
   at f.spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
   at spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
   at startPhantomProcess 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
   at Server.<anonymous> 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
   at emitNone (events.js:67:13)
   at Server.emit (events.js:166:7)
   at emitListeningNT (net.js:1260:10)
   at doNTCallback1 (node.js:430:9)
   at process._tickCallback (node.js:352:17)

Error: spawn UNKNOWN
   at exports._errnoException (util.js:874:11)
   at ChildProcess.spawn (internal/child_process.js:298:11)
   at exports.spawn (child_process.js:339:9)
   at f.spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
   at spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
   at startPhantomProcess 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
   at Server.<anonymous> 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
   at emitNone (events.js:67:13)
   at Server.emit (events.js:166:7)
   at emitListeningNT (net.js:1260:10)
   at doNTCallback1 (node.js:430:9)
   at process._tickCallback (node.js:352:17)

Error: spawn UNKNOWN
   at exports._errnoException (util.js:874:11)
   at ChildProcess.spawn (internal/child_process.js:298:11)
   at exports.spawn (child_process.js:339:9)
   at f.spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
   at spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
   at startPhantomProcess 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
   at Server.<anonymous> 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
   at emitNone (events.js:67:13)
   at Server.emit (events.js:166:7)
   at emitListeningNT (net.js:1260:10)
   at doNTCallback1 (node.js:430:9)
   at process._tickCallback (node.js:352:17)

Error: spawn UNKNOWN
   at exports._errnoException (util.js:874:11)
   at ChildProcess.spawn (internal/child_process.js:298:11)
   at exports.spawn (child_process.js:339:9)
   at f.spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
   at spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
   at startPhantomProcess 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
   at Server.<anonymous> 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
   at emitNone (events.js:67:13)
   at Server.emit (events.js:166:7)
   at emitListeningNT (net.js:1260:10)
   at doNTCallback1 (node.js:430:9)
   at process._tickCallback (node.js:352:17)

Error: spawn UNKNOWN
   at exports._errnoException (util.js:874:11)
   at ChildProcess.spawn (internal/child_process.js:298:11)
   at exports.spawn (child_process.js:339:9)
   at f.spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
   at spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
   at startPhantomProcess 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
   at Server.<anonymous> 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
   at emitNone (events.js:67:13)
   at Server.emit (events.js:166:7)
   at emitListeningNT (net.js:1260:10)
   at doNTCallback1 (node.js:430:9)
   at process._tickCallback (node.js:352:17)

Error: spawn UNKNOWN
   at exports._errnoException (util.js:874:11)
   at ChildProcess.spawn (internal/child_process.js:298:11)
   at exports.spawn (child_process.js:339:9)
   at f.spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\server.js:16:6560)
   at spawn 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\win-spawn\index.js:54:10)
   at startPhantomProcess 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:17:12)
   at Server.<anonymous> 
(C:\Users\user\.WebStorm2016.2\system\wallaby\wallaby\node_modules\phantom\phantom.js:115:14)
   at emitNone (events.js:67:13)
   at Server.emit (events.js:166:7)
   at emitListeningNT (net.js:1260:10)
   at doNTCallback1 (node.js:430:9)
   at process._tickCallback (node.js:352:17)

**Comment by ArtemGovorov** [comment]
Thanks for the log, it looks like there's an empty or corrupted phantomjs.exe is in the `C:\Users\user\.WebStorm2016.2\system\wallaby\phantomjs_v2.1.1` folder. Just delete the folder, restart your IDE and start wallaby, it should download and use the correct version.

**Comment by ochemerys** [comment]
Thank you very much.

It was exactly the issue and it works now !

Regards
